### ISSUE TITLE
JX die with a Benchmark

### ISSUE THREAD

**Issue by sebastianscatularo** [jxcore/jxcore#322] opened 2015-04-30 14:38 UTC
Hi everyone,
When I run the following code with node, it's work fine. But, when I run it with JX, the process is executed twice and the terminal stays blocked.
Am I doing something wrong?
This code try to make a benchmark to figure out the speed of FX and Node.

```JavaScript
var fs = require('fs');
var util = require('util');

var start = process.hrtime();

for(var i = 0; i < 100; i++) {
    (function(id) {
        fs.readdir('.', function() {
            var end = process.hrtime(start);
            console.log(util.format('readdir %d finished in %ds', id, end[0] + end[1] / 1e9));
        });
    })(i);
}                 
```

**Comment by sebastianscatularo** [comment] 2015-04-30 14:39
My JX version is:
$ jx -jxv
v Beta-0.2.3.7
$ jx -v
v0.10.32

Regards

**Comment by obastemur** [comment] 2015-04-30 20:43
@sebastianscatularo tried with the master (we will be releasing 1st of May) and it works.

v8 results:
```
readdir 0 finished in 0.004332002s
readdir 2 finished in 0.005978385s
readdir 1 finished in 0.006514503s
readdir 3 finished in 0.006658853s
readdir 4 finished in 0.006726004s
readdir 5 finished in 0.00678609s
readdir 6 finished in 0.006845131s
readdir 7 finished in 0.00689475s
readdir 8 finished in 0.006946587s
readdir 9 finished in 0.007003547s
readdir 10 finished in 0.007177578s
readdir 11 finished in 0.007207926s
readdir 12 finished in 0.007235842s
readdir 14 finished in 0.007264112s
readdir 13 finished in 0.007292085s
readdir 15 finished in 0.007319336s
readdir 16 finished in 0.007346835s
readdir 17 finished in 0.007374602s
readdir 18 finished in 0.007400049s
readdir 19 finished in 0.007427915s
readdir 20 finished in 0.007456274s
readdir 21 finished in 0.007485766s
readdir 22 finished in 0.007528682s
readdir 23 finished in 0.007559866s
readdir 24 finished in 0.007594145s
readdir 25 finished in 0.007622085s
readdir 26 finished in 0.007647298s
readdir 27 finished in 0.007675927s
readdir 29 finished in 0.007708338s
readdir 28 finished in 0.007736252s
readdir 31 finished in 0.007764213s
readdir 30 finished in 0.007792696s
readdir 32 finished in 0.007820322s
readdir 34 finished in 0.007861365s
readdir 33 finished in 0.007889601s
readdir 35 finished in 0.007913551s
readdir 36 finished in 0.007941395s
readdir 37 finished in 0.007969118s
readdir 38 finished in 0.007996852s
readdir 40 finished in 0.008024474s
readdir 39 finished in 0.008060014s
readdir 41 finished in 0.008100456s
readdir 42 finished in 0.008145293s
readdir 43 finished in 0.008183459s
readdir 44 finished in 0.008209847s
readdir 45 finished in 0.008267194s
readdir 46 finished in 0.008325469s
readdir 47 finished in 0.008378824s
readdir 48 finished in 0.008428246s
readdir 49 finished in 0.008479531s
readdir 50 finished in 0.008530828s
readdir 51 finished in 0.008583039s
readdir 52 finished in 0.008637304s
readdir 53 finished in 0.008683964s
readdir 54 finished in 0.008731141s
readdir 55 finished in 0.008778332s
readdir 56 finished in 0.008825335s
readdir 57 finished in 0.008873363s
readdir 58 finished in 0.00891347s
readdir 59 finished in 0.008942622s
readdir 60 finished in 0.008969919s
readdir 61 finished in 0.008999157s
readdir 62 finished in 0.009025626s
readdir 63 finished in 0.009054232s
readdir 64 finished in 0.009088772s
readdir 65 finished in 0.009141231s
readdir 67 finished in 0.00981295s
readdir 66 finished in 0.009855206s
readdir 68 finished in 0.009883858s
readdir 69 finished in 0.00991232s
readdir 70 finished in 0.009946609s
readdir 71 finished in 0.009996265s
readdir 72 finished in 0.0100445s
readdir 73 finished in 0.010093436s
readdir 74 finished in 0.01013905s
readdir 75 finished in 0.010188606s
readdir 76 finished in 0.010240443s
readdir 78 finished in 0.010292694s
readdir 77 finished in 0.010341145s
readdir 80 finished in 0.010394625s
readdir 79 finished in 0.010444247s
readdir 81 finished in 0.010492613s
readdir 82 finished in 0.01057916s
readdir 83 finished in 0.010608048s
readdir 84 finished in 0.010638983s
readdir 85 finished in 0.010666214s
readdir 86 finished in 0.010693233s
readdir 87 finished in 0.010723181s
readdir 88 finished in 0.010752441s
readdir 89 finished in 0.010779568s
readdir 90 finished in 0.01080605s
readdir 91 finished in 0.010832828s
readdir 92 finished in 0.010856714s
readdir 93 finished in 0.010884584s
readdir 94 finished in 0.010917533s
readdir 95 finished in 0.010961385s
readdir 96 finished in 0.010989258s
readdir 97 finished in 0.011014835s
readdir 98 finished in 0.011227912s
readdir 99 finished in 0.011267102s
```

SpiderMonkey results:
```
readdir 0 finished in 0.005082162s
readdir 1 finished in 0.005355688s
readdir 2 finished in 0.005515444s
readdir 3 finished in 0.005694308s
readdir 4 finished in 0.005764649s
readdir 5 finished in 0.005860058s
readdir 6 finished in 0.00599362s
readdir 7 finished in 0.006073276s
readdir 8 finished in 0.006144732s
readdir 9 finished in 0.006246216s
readdir 10 finished in 0.006356137s
readdir 11 finished in 0.007521708s
readdir 12 finished in 0.007671257s
readdir 13 finished in 0.007745731s
readdir 14 finished in 0.007803188s
readdir 15 finished in 0.007855045s
readdir 16 finished in 0.007909577s
readdir 17 finished in 0.007968366s
readdir 18 finished in 0.008021124s
readdir 19 finished in 0.008072251s
readdir 20 finished in 0.008121243s
readdir 21 finished in 0.008169737s
readdir 22 finished in 0.009192677s
readdir 23 finished in 0.009271595s
readdir 24 finished in 0.009322651s
readdir 25 finished in 0.009370747s
readdir 26 finished in 0.009417666s
readdir 27 finished in 0.009464249s
readdir 28 finished in 0.009515197s
readdir 29 finished in 0.009566539s
readdir 30 finished in 0.009617207s
readdir 31 finished in 0.009667952s
readdir 32 finished in 0.009714376s
readdir 33 finished in 0.00976029s
readdir 34 finished in 0.009812286s
readdir 35 finished in 0.009865832s
readdir 36 finished in 0.0099126s
readdir 37 finished in 0.009963252s
readdir 38 finished in 0.010010285s
readdir 39 finished in 0.010056395s
readdir 40 finished in 0.010110283s
readdir 41 finished in 0.010164337s
readdir 42 finished in 0.010220111s
readdir 43 finished in 0.010269971s
readdir 44 finished in 0.010315908s
readdir 45 finished in 0.010374898s
readdir 46 finished in 0.010423734s
readdir 47 finished in 0.010473098s
readdir 48 finished in 0.011764966s
readdir 49 finished in 0.01790132s
readdir 50 finished in 0.018014764s
readdir 51 finished in 0.018073387s
readdir 52 finished in 0.018114622s
readdir 53 finished in 0.018157681s
readdir 54 finished in 0.018196673s
readdir 55 finished in 0.018234115s
readdir 56 finished in 0.018279384s
readdir 57 finished in 0.0183216s
readdir 58 finished in 0.018361918s
readdir 59 finished in 0.01840307s
readdir 60 finished in 0.018440425s
readdir 61 finished in 0.018476273s
readdir 62 finished in 0.018512009s
readdir 63 finished in 0.018555921s
readdir 64 finished in 0.018592424s
readdir 65 finished in 0.018636704s
readdir 66 finished in 0.018673396s
readdir 67 finished in 0.018709116s
readdir 68 finished in 0.018749358s
readdir 69 finished in 0.018792739s
readdir 70 finished in 0.018829565s
readdir 71 finished in 0.018869209s
readdir 72 finished in 0.018905738s
readdir 73 finished in 0.018945927s
readdir 74 finished in 0.01898681s
readdir 75 finished in 0.019027036s
readdir 76 finished in 0.019063063s
readdir 77 finished in 0.01910244s
readdir 78 finished in 0.019139545s
readdir 79 finished in 0.019179217s
readdir 80 finished in 0.019222919s
readdir 81 finished in 0.01925933s
readdir 82 finished in 0.019299908s
readdir 83 finished in 0.019340204s
readdir 84 finished in 0.019376807s
readdir 85 finished in 0.019412244s
readdir 86 finished in 0.019455708s
readdir 87 finished in 0.019491714s
readdir 88 finished in 0.019527142s
readdir 89 finished in 0.019567142s
readdir 90 finished in 0.019607455s
readdir 91 finished in 0.019652984s
readdir 92 finished in 0.01968994s
readdir 93 finished in 0.0197258s
readdir 94 finished in 0.019761423s
readdir 95 finished in 0.019801466s
readdir 96 finished in 0.01983814s
readdir 97 finished in 0.019881055s
readdir 98 finished in 0.019921587s
readdir 99 finished in 0.019958239s
```

**Comment by ktrzeciaknubisa** [comment] 2015-05-01 07:45
Well, I have also tried with 2.3.7, and it works too. @sebastianscatularo Which is your operating system?

**Comment by ktrzeciaknubisa** [comment] 2015-05-14 14:10
I'm closing this one, since we cannot reproduce it. 

@sebastianscatularo Please try with the latest JXcore binaries available on [downloads](http://jxcore.com/downloads/). In case if the problem persists for you, feel free to reopen the issue with more details about your operating system.

**Closed by ktrzeciaknubisa** 2015-05-14 14:10 UTC
