### ISSUE TITLE
I would like to use the 'ref modules'. 

### ISSUE THREAD

**Issue by Kierian** [jxcore/jxcore#578] opened 2015-09-30 07:05 UTC
I'm Korean. Do not speak English well.
I used jx package ..
my project used ref modules.
i used command 'jx package project.js project -native'
i get error *.node ..
i used command 'jx package project.js project -native - slim ref
good compile but There is no reaction.

test/node_modules/ref installed..
test/project.exe

![noref](https://cloud.githubusercontent.com/assets/6712562/10186445/f8389762-678b-11e5-98d3-819eced0cf77.png)

my code deleted ref..
![noref](https://cloud.githubusercontent.com/assets/6712562/10186549/d1fc3ff8-678c-11e5-96f4-1e16baef7a6f.png)

It works well.

but my project need ref modules..

Why have a problem?

**Comment by ktrzeciaknubisa** [comment] 2015-09-30 08:37
Hi, I don't reproduce your error. Can you give few lines of the code which uses `ref` module and fails?

Also, I need some more info:

1. version of ref
2. version of JXcore (`jx -jxv && jx -jsv && jx -a`)  
3. is this Windows x64?

**Comment by Kierian** [comment] 2015-09-30 09:09
my code: 
encoder.prototype.WriteBigInteger = function (val) {
    var self = this;
    var buf = ref.alloc('int64');
    ref.writeInt64LE(buf, 0, val.toString());
    self.WriteBuf(buf, NetType.SizeOf.Int64);
};

1. version of ref : 2.11.3
2. version of JXcore : 0.3.0.5
3. Is this Windows x64 : windows8 64bit

Play step:
1. 
projectFolder>jx package project.js project -native -slim ref

2. 
test>jx install ref --msvs_version=2013

3. 
copy to test project.exe

4. 
test>project.exe

**Comment by Kierian** [comment] 2015-09-30 09:11
Additionally..
test>jx install ref --msvs_version=2013  : It works well.
but, project.jxp files.. edit preinstall : [ "jx install ref --msvs_version=2013" ] : npm error

**Comment by ktrzeciaknubisa** [comment] 2015-09-30 10:47
Thanks.

I thought we talk about this [ref](https://github.com/TooTallNate/ref) but it doesn't have 2.11.3 version. Which one then?

**Comment by Kierian** [comment] 2015-10-01 00:46
Oh sorry..;
my mistake; 2.11.3 is npm version
ref version is 1.1.1

**Comment by Kierian** [comment] 2015-10-01 02:27
all delete code and module.. and repository cloning code.
Play step 1234 .. I get new Error;
![newerror](https://cloud.githubusercontent.com/assets/6712562/10211406/ec1a3858-682d-11e5-92b7-07c696f602bd.png)

after...

I edited binding.js:
 try: [
          // node-gyp's linked version in the "build" dir
          [ 'module_root', 'build', 'bindings' ]
          // node-waf and gyp_addon (a.k.a node-gyp)
        , [ 'module_root', 'build', 'Debug', 'bindings' ]
        , [ 'module_root', 'build', 'Release', 'bindings' ]
          // Debug files, for development (legacy behavior, remove for node v0.9)
        , [ 'module_root', 'out', 'Debug', 'bindings' ]
        , [ 'module_root', 'Debug', 'bindings' ]
          // Release files, but manually compiled (legacy behavior, remove for node v0.9)
        , [ 'module_root', 'out', 'Release', 'bindings' ]
        , [ 'module_root', 'Release', 'bindings' ]
          // Legacy from node-waf, node <= 0.4.x
        , [ 'module_root', 'build', 'default', 'bindings' ]
          // Production "Release" buildtype binary (meh...)
        , [ 'module_root', 'compiled', 'version', 'platform', 'arch', 'bindings' ]
        ] 
->
 try: [
         [ 'module_root', 'build', 'Release', 'bindings' ]
        ] 

my code 'binding.node' is build/release folder...
I guessed throw code isn't hit...but appear same error... 
panic ..ToT.. plz help me

**Comment by Kierian** [comment] 2015-10-01 02:59
'jx install --msvs_version=2013' not a reaction like I did the first attachment.
![jx](https://cloud.githubusercontent.com/assets/6712562/10211933/b72f9a1a-6833-11e5-8789-cd7aca267554.png)

'npm install --msvs_version=2013' produces a second error.
![npm](https://cloud.githubusercontent.com/assets/6712562/10211934/b72fc9ea-6833-11e5-8d28-30f43a17a828.png)

jx install , npm install not same ...

**Comment by ktrzeciaknubisa** [comment] 2015-10-01 14:07
Thanks for all the data. 

Native packages may still have some problems with *.node* files - see: https://github.com/jxcore/jxcore/issues/489. Until it will be fixed, you may try to use regular jx package (anyway you have JXcore installed on target machine since you planned to use `preinstall` with `jx install`).

So what I can advice you in this moment, is to use self-extractable package, like this:

```bash
$ jx package project.js --extract-what "*.node" --extract-app-root
```

Now you have `project.jx` and you can copy it somewhere and run `jx package.jx`. All *.node* files will get extracted on first run.

Let me know if that satisfies you.

**Comment by ktrzeciaknubisa** [comment] 2015-10-01 14:08
One more thing: please upgrade to JXcore 0.3.0.7 and use `jx install` instead of `npm install`.

**Comment by Kierian** [comment] 2015-10-02 01:01
thanks for your help. 
I try this way

**Comment by ktrzeciaknubisa** [comment] 2015-10-30 16:18
@Kierian did it work for you? Can we close it?

**Closed** 2015-11-02 00:56 UTC
