### ISSUE TITLE
jx_install.sh error: Could not fetch

### ISSUE THREAD

**Issue by shizonic** [jxcore/jxcore#913] opened 2016-10-11 10:25 UTC
While trying to install with the help of the jx_install.sh script I get an error:

`Could not fetch`

The reason might be the fact that "https://jxcore.s3.amazonaws.com/latest.txt" throws an error "No such bucket".

**Comment by jasonkarns** [comment] 2016-10-11 17:11
dupe of #912

**Closed by jasonkarns** 2016-10-11 17:11 UTC
