### ISSUE TITLE
Bug in net server socket data handling

### ISSUE THREAD

**Issue by yaronyg** [jxcore/jxcore#411] opened 2015-06-20 23:51 UTC
I ran into an odd bug with server socket data handling. I ran the following code on the JXCore desktop (OS/X) and it ran just fine:

```node.js
exports.startSocketServer = function(port) {
    var server = net.createServer(function(incomingClientSocket) {
        console.log("We have a incomingClientSocket connection!");

        incomingClientSocket.on('end', function() {
            console.log("We lost a incomingClientSocket connection.");
        });
        
        incomingClientSocket.pipe(incomingClientSocket);
    });

    server.listen(port);

    return server;
};
```
For what it's worth the above code also ran fine on Node 0.10 and 0.12.

But when I ran the exact same code on Android using jxcore-cordova it failed! My client could write data but the data never appeared to arrive. While debugging I accidentally found a work around. Which is:

```node.js
exports.startSocketServer = function(port) {
    var server = net.createServer(function(incomingClientSocket) {
        console.log("We have a incomingClientSocket connection!");

        incomingClientSocket.on('end', function() {
            console.log("We lost a incomingClientSocket connection.");
        });

        incomingClientSocket.on('data', function(data) {
            // BUGBUG: On the desktop this event listener is not necessary. But on JXCore on Android
            // we have to include this handler or no data will ever arrive at the server.
        });
        
        incomingClientSocket.pipe(incomingClientSocket);
    });

    server.listen(port);

    return server;
};
```

The difference is the listener with the BugBug. Please notice that the event listener isn't actually doing anything but just by virtue of existing suddenly the data flows.

**Comment by obastemur** [comment] 2015-06-21 03:09
Interesting. Looks like a timing issue. Looking into it.

**Comment by obastemur** [comment] 2015-06-22 10:25
@yaronyg I believe there is no bug here. Please see the below code (same behavior for JXcore desktop, android and node.JS)

```
var assert = require('assert');
var net = require('net');

var kPoolSize = 40 * 1024;
var data = '';
for (var i = 0; i < kPoolSize; ++i) {
  data += 'あ'; // 3bytes
}
var receivedSize = 0;
var encoding = 'UTF-8';

var server = net.createServer(function(socket) {
  socket.setEncoding(encoding);
  socket.on('data', function(data) {
    receivedSize += data.length;
  });
  socket.on('end', function() {
    socket.end();
  });

  socket.pipe(socket);

});

server.listen(1134, function() {
  var client = net.createConnection(1134);
  client.on('end', function() {
    server.close();
  });

  // IF YOU DONT ENABLE BELOW, APP WILL RUN FOREVER
  //client.on('data', function(data){
  //  console.log("!!", data.length)
  //})

  client.write(data, encoding);
  client.end();
});

process.on('exit', function() {
  assert.equal(receivedSize, kPoolSize);
});
```

**Comment by yaronyg** [comment] 2015-06-22 16:48
There is a bug and I can give you a 100% repro.

If you comment out https://github.com/thaliproject/Thali_CordovaPlugin/blob/c0d0da2d01194aeaa3d73163605f0d8bd06f6042/test/sockettest.js#L22-L27 then the test code will fail on Android. If you leave those lines in then the code will pass.

Note that if you comment out that code on Node.js 0.10, Node.js 0.12 or JXCore latest it will pass.

So 100% there is a bug. We should not be seeing this code pass on the desktop and have the exact same code fail on Android.

BTW, this code was actually taken from the example in the Node.js documentation. So basically JXCore on Android fails on Node.js reference code!

**Comment by obastemur** [comment] 2015-06-22 16:55
On my sample above it also requires the 'data' handler is defined. Otherwise it wouldn't finish. The problem is socket is piping back and there is no consumer.

**Comment by yaronyg** [comment] 2015-06-22 17:04
@obastemur I think we are talking past each other.

This is really simple. If Code X works on Node.js/JXCore on the desktop and the exact, line by line, code doesn't work on JXCore on Android then there is a bug.

That is the situation here.

BTW, there is a consumer. In the example the pipe is only created when there is a TCP/IP client who is consuming it. Which is why the code works just fine on Node.js without defining a data handler.

There is a bug in JXCore on Android that if you don't define a data handler then no data flows. That is NOT the behavior exhibited by Node.js or JXCore on the desktop. So again, there is a bug.

**Comment by obastemur** [comment] 2015-06-23 18:18
Closing this one for now since I was unable to reproduce it. Thanks for all the details

**Comment by ktrzeciaknubisa** [comment] 2015-06-24 09:26
@yaronyg I've tried your scenario too with jxcore-cordova (Samsung Galaxy S II, ARMv7 Processor rev 1 (v7l), Android 4.1.2), and I wasn't able to observe the behavior you mention. Works for me the same with or without `incomingClientSocket.on('data')`. If you still get this, maybe this is device specific?

However I thought of one other thing: you start to listen to your server `server.listen(port)` but you don't attach to `server.on("listening")` event so at least in theory it is possible, that client connect's to server, which is not ready yet?

**Comment by obastemur** [comment] 2015-06-24 10:39
> so at least in theory it is possible, that client connect's to server, which is not ready yet?
@ktrzeciaknubisa can you elaborate this?

**Comment by ktrzeciaknubisa** [comment] 2015-06-24 10:51
My idea was, that any client's connection attempt should take place on `listening` event (once we're sure, that the server started to listen - like in your @obastemur sample above):

```js
server.listen(port, function() { //'listening' listener
 var client = net.createConnection(port);
});
```

While in @yaronyg approach [sockettest.js#L189-L190](https://github.com/thaliproject/Thali_CordovaPlugin/blob/c0d0da2d01194aeaa3d73163605f0d8bd06f6042/test/sockettest.js#L189-L190) I just see the concept analogous to:
```js
server.listen(port);
var client = net.createConnection(port);
```
But even so, it still worked on my android device with cordova.

**Comment by obastemur** [comment] 2015-06-24 10:53
yep it makes sense. Especially on jxcore-cordova bridge where we do not pull io on main thread in real time.

**Comment by yaronyg** [comment] 2015-06-24 15:41
@ktrzeciaknubisa thanks for thinking of this but I believe I can prove that isn't the case. The reason is this sample from my error log:

```
06-24 05:35:50.184  10102-10102/com.test.thalitest I/jxcore-log﹕ We have a incomingClientSocket connection!
06-24 05:35:50.184  10102-10102/com.test.thalitest I/jxcore-log﹕ We have successfully connected to the server.
06-24 05:37:55.216  10102-10102/com.test.thalitest I/jxcore-log﹕ About to retry because of: Error: Timeout before Passing
```

If the client was attempting to connect to the server before the server was ready to listen then we would never get the "We have a incomingClientSocket connection!" message or the "We have successfully connected to the server." So we know that the client is always successful in connecting.

My main test device is a Samsung S4 running 4.3. 

For chuckles I ran the same test on my other device, a Nexus 7 running 4.4.4. I get the exact same error there as well.

What I wonder is if one error is interfering with another? In the test I have up and running my full log looks like:

```
06-24 08:29:34.467  21972-21972/com.test.thalitest W/jxcore-log﹕ Initializing JXcore engine
06-24 08:29:34.467  21972-21972/com.test.thalitest W/jxcore-log﹕ JXcore engine is ready
06-24 08:29:34.517  21972-21972/com.test.thalitest D/dalvikvm﹕ GC_FOR_ALLOC freed 252K, 15% free 15438K/18064K, paused 27ms, total 27ms
06-24 08:29:34.517  21972-21972/com.test.thalitest W/jxcore-log﹕ Starting JXcore engine
06-24 08:29:34.737  21972-21972/com.test.thalitest W/jxcore-log﹕ Platform android
06-24 08:29:34.737  21972-21972/com.test.thalitest W/jxcore-log﹕ Process ARCH arm
06-24 08:29:35.308  21972-21972/com.test.thalitest I/jxcore-log﹕ JXcore Cordova Bridge is Ready!
06-24 08:29:35.308  21972-21972/com.test.thalitest W/jxcore-log﹕ JXcore engine is started
06-24 08:29:35.358  21972-21972/com.test.thalitest E/qdutils﹕ FBIOGET_FSCREENINFO failed
06-24 08:29:35.398  21972-21972/com.test.thalitest I/jxcore-log﹕ loadMainFile app.js
06-24 08:29:35.788  21972-21972/com.test.thalitest I/jxcore-log﹕ GetDeviceName return was Nexus 7
06-24 08:29:44.246  21972-21972/com.test.thalitest I/jxcore-log﹕ ThaliMobile app.js loaded
06-24 08:29:44.246  21972-21972/com.test.thalitest I/Choreographer﹕ Skipped 531 frames!  The application may be doing too much work on its main thread.
06-24 08:29:44.277  21972-21972/com.test.thalitest I/jxcore-log﹕ undefined
06-24 08:29:44.277  21972-21972/com.test.thalitest E/jxcore-log﹕ Error:
06-24 08:29:44.277  21972-21972/com.test.thalitest E/jxcore-log﹕ EROFS, open './log.txt'
06-24 08:29:44.277  21972-21972/com.test.thalitest E/jxcore-log﹕ (native:jxcore_js_object 3:11)
06-24 08:29:44.277  21972-21972/com.test.thalitest E/jxcore-log﹕ [ 06-24 08:29:44.957 21972:21972 I/chromium ]
    [INFO:CONSOLE(1188)] "deviceready has not fired after 5 seconds.", source: file:///android_asset/www/cordova.js (1188)
06-24 08:29:44.957  21972-21972/com.test.thalitest I/chromium﹕ [INFO:CONSOLE(1181)] "Channel not fired: onJXcoreReady", source: file:///android_asset/www/cordova.js (1181)
06-24 08:29:44.957  21972-21972/com.test.thalitest I/Choreographer﹕ Skipped 41 frames!  The application may be doing too much work on its main thread.
06-24 08:29:44.977  21972-21972/com.test.thalitest I/jxcore-log﹕ We have a incomingClientSocket connection!
06-24 08:29:44.987  21972-21972/com.test.thalitest I/jxcore-log﹕ We have successfully connected to the server.
06-24 08:31:49.339  21972-21972/com.test.thalitest I/jxcore-log﹕ About to retry because of: Error: Timeout before Passing
```

So I'm getting other errors that theoretically aren't a part of the test I'm running. They are from surrounding code.

Could they be interfering? And if so why does sticking in on('data' fix things?

**Comment by obastemur** [comment] 2015-06-24 15:47
```
06-24 08:29:44.277  21972-21972/com.test.thalitest E/jxcore-log﹕ Error:
06-24 08:29:44.277  21972-21972/com.test.thalitest E/jxcore-log﹕ EROFS, open './log.txt'
06-24 08:29:44.277  21972-21972/com.test.thalitest E/jxcore-log﹕ (native:jxcore_js_object 3:11)
```

This is an unhandled exception and breaks the flow. In other words, once it happens on 'desktop' it would kill the process unless there is a mechanism to manage unhandled exceptions. However on mobile, it just throws and breaks the execution.

**Comment by yaronyg** [comment] 2015-06-24 17:15
Then why does sticking the data listener back in suddenly solve things? Because I get the same errors when I have the data listener is included and the test passes.

**Comment by obastemur** [comment] 2015-06-24 17:53
I can't tell anything on this part. I wish I could reproduce the issue.

**Comment by obastemur** [comment] 2015-06-24 17:55
I'm keeping this issue open until it disappears on your end.

**Comment by yaronyg** [comment] 2015-06-24 18:12
So I just reran the test using Jukka's latest code. I got all the bits completely fresh. In that case the bug doesn't repro BUT his latest code doesn't include any of the buggy PouchDB calls. My guess is that there is something wrong in JXCore's error handling that causes it to get into a weird state when an unhandled node.js exception is thrown but there are still registered event handlers and listeners. But I'm going to close this until it shows up again.

**Comment by obastemur** [comment] 2015-06-24 18:17
Okay tracking the suggested issue on https://github.com/jxcore/jxcore/issues/414 . Thanks @yaronyg for all the details.

**Comment by yaronyg** [comment] 2015-07-09 20:18
I just ran into another version of this bug. The Thali replication manager is an event emitter. But nobody was subscribed to any of its events. Which shouldn't matter because they are just informational. The replication manager would start running, we could see it made a call to native code and then that was it. Nothing. Then I put a listener on it for debugging purposes and immediately everything started working just fine! If I remove the listener then everything stops working again. Something is wrong with the emiter logic in JXCore. It gets "stuck" if nobody listens.

**Comment by nzhome** [comment] 2015-09-03 09:19
from an outsiders view, this sounds like a timing bug...   @obastemur has different speed device than @yaronyg     its a pity, because I bet @obastemur could resolve it, but if only he could reproduce.  what model and speed is your device yaronyg?

**Comment by obastemur** [comment] 2015-09-03 10:04
AFAIK this is no longer an issue. @yaronyg  ?

**Comment by yaronyg** [comment] 2015-09-08 20:53
So much has changed since I filed this that I don't have a clean repro at the moment. :(

**Comment by obastemur** [comment] 2015-09-09 07:12
Closing for now.

**Closed by obastemur** 2015-09-09 07:12 UTC

**Comment by nzhome** [comment] 2015-09-09 07:39
and that folks, is how instability creeps into software projects.  people don't have the skills to investigate or correctly log and debug known issues. some other devs I know get lazy and too easily close issues that don't happen on their environment instead of adding more debug statements to capture the known issue in one area of the codebase.

**Comment by obastemur** [comment] 2015-09-09 09:17
We have all the known Android, iOS (4S+) devices. If in any case, anyone can send me something reproducible, I can gladly look into that.
