### ISSUE TITLE
node require broken in Windows version of JXCore 3.0.0/3.0.1

### ISSUE THREAD

**Issue by hacker112** [jxcore/jxcore#379] opened 2015-06-04 13:09 UTC
The node require function breaks when running jx package on Windows with version 3.0.0 or 3.0.1, but works fine in 2.3.7. The require works with 3.0.1 when used om Mac OS X. So something has changed between 2.3.7 and 3.0 in the windows version.

This is what I see happens hand what breaks my code.
require sometimes loads a file again, which breaks functionality that depends on a previous state in a module. In my case settings that are stored in a module during runtime. The first and and second time it loads the same file/object from memory but the third time it reload the file. It also breaks something similar in the npm package called debug.

**Comment by obastemur** [comment] 2015-06-04 13:17
@hacker112 can you provide a simple test case to reproduce?

**Comment by obastemur** [comment] 2015-06-04 13:39
I couldn't reproduce it (SM, V8)..

My test scenario was;

hey.js
```
console.log("hey!");
```

index.js
```
var count = 0;
setInterval(function() {
  if (count++ > 100) process.exit(0);
  require('./hey');
}, 100);
```

As expected I saw 'hey!' only once.

**Comment by hacker112** [comment] 2015-06-04 13:43
I will see if I can reproduce it. I can sadly not give you our private code. But I will see if I can reproduce it in a smaller scale. As you say a simple multiple require does not reproduce it. There is something more that causes this.

**Comment by obastemur** [comment] 2015-06-04 13:45
What we / node does is a simple absolute path comparison. Is this a JX package or a project on file system?

**Comment by hacker112** [comment] 2015-06-04 13:50
This happens when I run the jx package (version 3.0.1). It works fine in plain node and works fine in jx 2.3.7. So when this happens everything should be in the js package.

**Comment by obastemur** [comment] 2015-06-04 14:36
Also couldn't reproduce it under a JX package. We definitely need a test case. Thanks!

**Comment by eajimmy** [comment] 2015-06-09 14:05
Hi @obastemur, @hacker112, 
I think I have this same issue and I made an example.
In [this zip](https://mega.co.nz/#!T492FTqR!28hq3-2Ju4NbLsd-GR3Fs8B_N1hevGs0ECexGnQyLLs) you will find this project:
-- toRequire.js
-- lvl1
----|-- lvl2
--------|-- bridge.js
--------|-- index.js

and the jx versions already compiled to work with jxcore 0.2.3.7 and 0.3.0.2.

the toRequire.js is a simple module that exports some node modules.
the bridge.js requires the toRequire.js and adds a property test: "test".
the index.js requires both files and logs the content of test.

I've added some folder structure because reasons ;-)

The expected result is that the index should have the test property set, and this is what happens with the unpackaged version and the working, compiled 0.2.3.7 version.

The same project compiled with the latest 0.3.0.2 release doesn't work: test property is undefined from index.js.

P.S.: 
The issue happens only on windows; the project works with all versions on Linux (tested with Debian Jessie)

Thank you

**Comment by ktrzeciaknubisa** [comment] 2015-06-09 14:21
Hi @eajimmy Thanks for the sample. I've run it with today's commit de2b1ffb3c3df4f13edf9af1ae6a9f0b6bf7abf4 and seems working for me:

```bash
REQUIRE FROM BRIDGE: test
REQUIRE FROM INDEX: test
```
While with previous binary i get different output (incorrect, I assume):

```bash
REQUIRE FROM BRIDGE: test
REQUIRE FROM INDEX: undefined
```

Could you please recompile the latest and let us know?

**Comment by eajimmy** [comment] 2015-06-09 14:54
I've just tested it with my real code and it works like a charm! 

Thank you!

**Comment by ktrzeciaknubisa** [comment] 2015-06-09 15:09
Thank you @eajimmy .

@hacker112 How about you? Are you able to compile JXcore from master and test your scenario?

**Comment by hacker112** [comment] 2015-06-09 15:31
@ktrzeciaknubisa I don't have the time to test now, but I have the have looked at the diff and it seems like it is related. and the sample by @eajimmy seems similar to my code structure :-) Thanks!

**Comment by ktrzeciaknubisa** [comment] 2015-06-09 15:41
Ok, thanks @hacker112 . Then I'm closing it for now, however please feel free to reopen in case of further problems. Thanks!

**Closed by ktrzeciaknubisa** 2015-06-09 15:41 UTC
