### ISSUE TITLE
Can't install ffi

### ISSUE THREAD

**Issue by zamb3zi** [jxcore/jxcore#359] opened 2015-05-23 08:55 UTC
Hi, I'm trying to install [ffi](https://www.npmjs.com/package/ffi) with the latest jxcore build and can't get it to work. After a fresh build, I perform a local install as follows:
```
C:\>users\zamb3zi\Documents\stats\jxcore\Release\jx.exe install ffi
Preparing NPM for JXcore (v Beta-0.3.0.1) for the first run
Downloading NPM for JXcore
..
NPM for JX is ready.
executing... please wait.
npm WARN invalid config local-address=undefined
npm http GET https://registry.npmjs.org/ffi
npm http 304 https://registry.npmjs.org/ffi
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/ref
npm http GET https://registry.npmjs.org/ref-struct
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/ref
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/ref-struct
npm http GET https://registry.npmjs.org/ms
|


> ref@1.0.2 install C:\node_modules\ffi\node_modules\ref
> node-gyp rebuild

-
C:\node_modules\ffi\node_modules\ref>jx "C:\Users\zamb3zi\.jx\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gy
p.js" rebuild
gyp http GET https://nodejx.s3.amazonaws.com/jxb300.tar.gz
gyp http 200 https://nodejx.s3.amazonaws.com/jxb300.tar.gz
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  binding.cc
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ exception handler used,
 but unwind semantics are not enabled. Specify /EHsc [C:\node_modules\ffi\node_modules\ref\build\binding.vcxproj]
c:\users\zamb3zi\.node-gyp\jxb300\src\jx\btree.h(918): warning C4099: 'btree::btree_internal_locate_plain_compare' : type
name first seen using 'struct' now seen using 'class' [C:\node_modules\ffi\node_modules\ref\build\binding.vcxproj]
          c:\users\zamb3zi\.node-gyp\jxb300\src\jx\btree.h(893) : see declaration of 'btree::btree_internal_locate_plain_c
  ompare'
          c:\users\zamb3zi\.node-gyp\jxb300\src\jx\btree.h(1493) : see reference to class template instantiation 'btree::b
  tree<Params>' being compiled
c:\users\zamb3zi\.node-gyp\jxb300\src\jx\btree.h(919): warning C4099: 'btree::btree_internal_locate_compare_to' : type nam
e first seen using 'struct' now seen using 'class' [C:\node_modules\ffi\node_modules\ref\build\binding.vcxproj]
          c:\users\zamb3zi\.node-gyp\jxb300\src\jx\btree.h(901) : see declaration of 'btree::btree_internal_locate_compare
  _to'
c:\users\zamb3zi\.node-gyp\jxb300\src\v8.h(179): warning C4506: no definition for inline function 'v8::Persistent<v8::Obje
ct> v8::Persistent<v8::Object>::New(v8::Handle<v8::Object>)' [C:\node_modules\ffi\node_modules\ref\build\binding.vcxpro
j]
c:\users\zamb3zi\.node-gyp\jxb300\src\v8.h(179): warning C4506: no definition for inline function 'v8::Persistent<v8::Func
tionTemplate> v8::Persistent<v8::FunctionTemplate>::New(v8::Handle<v8::FunctionTemplate>)' [C:\node_modules\ffi\node_mo
dules\ref\build\binding.vcxproj]
     Creating library C:\node_modules\ffi\node_modules\ref\build\Release\binding.lib and object C:\node_modules\ffi\nod
  e_modules\ref\build\Release\binding.exp
  Generating code
  Finished generating code
  binding.vcxproj -> C:\node_modules\ffi\node_modules\ref\build\Release\\binding.node
npm http 304 https://registry.npmjs.org/ms


> ffi@1.3.1 install C:\node_modules\ffi
> node-gyp rebuild

|
C:\node_modules\ffi>jx "C:\Users\zamb3zi\.jx\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  dlfcn.c
  dlfcn.vcxproj -> C:\node_modules\ffi\build\Release\\dlfcn.lib
  Building assembly file C:\node_modules\ffi\deps\libffi\src\x86\win32.asm
  prep_cif.c
  types.c
  raw_api.c
  java_raw_api.c
  closures.c
  ffi.c
  ffi.vcxproj -> C:\node_modules\ffi\build\Release\\libffi.lib
  ffi.cc
  callback_info.cc
  threaded_callback_invokation.cc
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ exception handler used,
 but unwind semantics are not enabled. Specify /EHsc (..\src\ffi.cc) [C:\node_modules\ffi\build\ffi_bindings.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ exception handler used,
 but unwind semantics are not enabled. Specify /EHsc (..\src\threaded_callback_invokation.cc) [C:\node_modules\ffi\buil
d\ffi_bindings.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xlocale(337): warning C4530: C++ exception handler used,
 but unwind semantics are not enabled. Specify /EHsc (..\src\callback_info.cc) [C:\node_modules\ffi\build\ffi_bindings.
vcxproj]
c:\users\zamb3zi\.node-gyp\jxb300\src\jx\btree.h(918): warning C4099: 'btree::btree_internal_locate_plain_compare' : type
name first seen using 'struct' now seen using 'class' (..\src\ffi.cc) [C:\node_modules\ffi\build\ffi_bindings.vcxproj]
          c:\users\zamb3zi\.node-gyp\jxb300\src\jx\btree.h(893) : see declaration of 'btree::btree_internal_locate_plain_c
  ompare'
          c:\users\zamb3zi\.node-gyp\jxb300\src\jx\btree.h(1493) : see reference to class template instantiation 'btree::b
  tree<Params>' being compiled
c:\users\zamb3zi\.node-gyp\jxb300\src\jx\btree.h(919): warning C4099: 'btree::btree_internal_locate_compare_to' : type nam
e first seen using 'struct' now seen using 'class' (..\src\ffi.cc) [C:\node_modules\ffi\build\ffi_bindings.vcxproj]
          c:\users\zamb3zi\.node-gyp\jxb300\src\jx\btree.h(901) : see declaration of 'btree::btree_internal_locate_compare
  _to'
c:\users\zamb3zi\.node-gyp\jxb300\src\jx\btree.h(918): warning C4099: 'btree::btree_internal_locate_plain_compare' : type
name first seen using 'struct' now seen using 'class' (..\src\threaded_callback_invokation.cc) [C:\node_modules\ffi\bui
ld\ffi_bindings.vcxproj]
          c:\users\zamb3zi\.node-gyp\jxb300\src\jx\btree.h(893) : see declaration of 'btree::btree_internal_locate_plain_c
  ompare'
          c:\users\zamb3zi\.node-gyp\jxb300\src\jx\btree.h(1493) : see reference to class template instantiation 'btree::b
  tree<Params>' being compiled
c:\users\zamb3zi\.node-gyp\jxb300\src\jx\btree.h(919): warning C4099: 'btree::btree_internal_locate_compare_to' : type nam
e first seen using 'struct' now seen using 'class' (..\src\threaded_callback_invokation.cc) [C:\node_modules\ffi\build\
ffi_bindings.vcxproj]
          c:\users\zamb3zi\.node-gyp\jxb300\src\jx\btree.h(901) : see declaration of 'btree::btree_internal_locate_compare
  _to'
c:\users\zamb3zi\.node-gyp\jxb300\src\jx\btree.h(918): warning C4099: 'btree::btree_internal_locate_plain_compare' : type
name first seen using 'struct' now seen using 'class' (..\src\callback_info.cc) [C:\node_modules\ffi\build\ffi_bindings
.vcxproj]
          c:\users\zamb3zi\.node-gyp\jxb300\src\jx\btree.h(893) : see declaration of 'btree::btree_internal_locate_plain_c
  ompare'
          c:\users\zamb3zi\.node-gyp\jxb300\src\jx\btree.h(1493) : see reference to class template instantiation 'btree::b
  tree<Params>' being compiled
c:\users\zamb3zi\.node-gyp\jxb300\src\jx\btree.h(919): warning C4099: 'btree::btree_internal_locate_compare_to' : type nam
e first seen using 'struct' now seen using 'class' (..\src\callback_info.cc) [C:\node_modules\ffi\build\ffi_bindings.vc
xproj]
          c:\users\zamb3zi\.node-gyp\jxb300\src\jx\btree.h(901) : see declaration of 'btree::btree_internal_locate_compare
  _to'
c:\users\zamb3zi\.node-gyp\jxb300\src\v8.h(179): warning C4506: no definition for inline function 'v8::Persistent<v8::Obje
ct> v8::Persistent<v8::Object>::New(v8::Handle<v8::Object>)' (..\src\threaded_callback_invokation.cc) [C:\node_modules\
ffi\build\ffi_bindings.vcxproj]
c:\users\zamb3zi\.node-gyp\jxb300\src\v8.h(179): warning C4506: no definition for inline function 'v8::Persistent<v8::Func
tionTemplate> v8::Persistent<v8::FunctionTemplate>::New(v8::Handle<v8::FunctionTemplate>)' (..\src\threaded_callback_in
vokation.cc) [C:\node_modules\ffi\build\ffi_bindings.vcxproj]
c:\users\zamb3zi\.node-gyp\jxb300\src\v8.h(179): warning C4506: no definition for inline function 'v8::Persistent<v8::Obje
ct> v8::Persistent<v8::Object>::New(v8::Handle<v8::Object>)' (..\src\ffi.cc) [C:\node_modules\ffi\build\ffi_bindings.vc
xproj]
c:\users\zamb3zi\.node-gyp\jxb300\src\v8.h(179): warning C4506: no definition for inline function 'v8::Persistent<v8::Func
tionTemplate> v8::Persistent<v8::FunctionTemplate>::New(v8::Handle<v8::FunctionTemplate>)' (..\src\ffi.cc) [C:\node_mod
ules\ffi\build\ffi_bindings.vcxproj]
c:\users\zamb3zi\.node-gyp\jxb300\src\v8.h(179): warning C4506: no definition for inline function 'v8::Persistent<v8::Obje
ct> v8::Persistent<v8::Object>::New(v8::Handle<v8::Object>)' (..\src\callback_info.cc) [C:\node_modules\ffi\build\ffi_b
indings.vcxproj]
c:\users\zamb3zi\.node-gyp\jxb300\src\v8.h(179): warning C4506: no definition for inline function 'v8::Persistent<v8::Func
tionTemplate> v8::Persistent<v8::FunctionTemplate>::New(v8::Handle<v8::FunctionTemplate>)' (..\src\callback_info.cc) [C
:\node_modules\ffi\build\ffi_bindings.vcxproj]
     Creating library C:\node_modules\ffi\build\Release\ffi_bindings.lib and object C:\node_modules\ffi\build\Release\f
  fi_bindings.exp
  Generating code
  Finished generating code
  ffi_bindings.vcxproj -> C:\node_modules\ffi\build\Release\\ffi_bindings.node
ffi@1.3.1 node_modules\ffi
├── bindings@1.2.1
├── ref-struct@1.0.1
├── nan@1.8.4
├─┬ debug@2.2.0
│ └── ms@0.7.1
└── ref@1.0.2

C:\>users\zamb3zi\Documents\stats\jxcore\Release\jx.exe
> require('ffi')
Error: The specified module could not be found.
c:\node_modules\ffi\node_modules\ref\build\release\binding.node
    at Object.process.dlopen [as .node] (node.js:692:25)
    at Module.load (module.js:346:36)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:378:17)
    at require (module.js:396:17)
    at bindings (C:\node_modules\ffi\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (C:\node_modules\ffi\node_modules\ref\lib\ref.js:5:47)
    at Module._compile (module.js:519:26)
    at Object.Module._extensions..js (module.js:549:10)
    at Module.load (module.js:346:36)
>
C:\>dir c:\node_modules\ffi\node_modules\ref\build\release
 Volume in drive C has no label.
 Volume Serial Number is 6AD0-CF80

 Directory of c:\node_modules\ffi\node_modules\ref\build\release

23/05/2015  15:40    <DIR>          .
23/05/2015  15:40    <DIR>          ..
23/05/2015  15:40               679 binding.exp
23/05/2015  15:40             1,698 binding.lib
23/05/2015  15:40           113,664 binding.node
23/05/2015  15:40         1,788,928 binding.pdb
23/05/2015  15:40    <DIR>          obj
               4 File(s)      1,904,969 bytes
               3 Dir(s)  14,050,238,464 bytes free
```

FFI was working before. If I install instead with `npm install ffi` then the resulting package works with both node and the installed version of jxcore (v Beta-0.2.3.7). With the trunk build of jxcore, the program exits silently upon `require('ffi')`. Thanks for any help!

**Comment by obastemur** [comment] 2015-05-23 10:28
I did exactly the same but have different set of files;

![ffi_scr1](https://cloud.githubusercontent.com/assets/4390745/7783575/f5d49652-0146-11e5-8c19-ba14c1f811d9.png)

Could you check if you have ffi_bindings.node ?

**Comment by zamb3zi** [comment] 2015-05-23 10:34
Hi, yes I have the same files in `node_modules\ffi\build\release` but the problem file seems to be `node_modules\ffi\node_modules\ref\build\release\binding.node`.

**Comment by obastemur** [comment] 2015-05-23 14:09
I don't have that 'ref' folder. Could you please delete ffi folder entirely and try a clean install?

**Comment by zamb3zi** [comment] 2015-05-24 04:41
I've just re-cloned jxcore, edited `PATH` to remove any installed node, npm or jxcore directories, `vcbuild.bat x86`. Deleted the local `node_modules`, `%APPDATA%\npm`, `%APPDATA%\npm-cache`, `%HOMEPATH%\.jx`, `%HOMEPATH%\.node-gyp`. I get exactly the same error.

You probably don't have `ref` installed as a sub-module because you already have it installed as a main module. If we forget about `ffi`, I have the same problem installing `ref` directly.

So, if I delete the local `node_modules` then `jx.exe install ref`, it seems to install and build properly as above, however `jx.exe -p require('ref')` produces the same error. Opening the installed `node_modules\ref\build\Release\binding.node` file in [Dependency Walker](http://www.dependencywalker.com/) I see that it links to `JX.DLL` but I haven't built the DLL, I built `jx.exe`. When I install `ref` with `npm`, it links to `node.exe` as expected and it works fine. Note: I'm building 32-bit jxcore on a 64-bit windows machine. Any thoughts?

**Comment by zamb3zi** [comment] 2015-05-24 05:05
Update: compiling 64-bit jxcore instead works! Installing `ref` produces a `node_modules\ref\build\Release\binding.node` which links to `JX.EXE`.

**Comment by zamb3zi** [comment] 2015-05-24 05:50
The problem seems to be the downloaded `%HOMEPATH%\.node-gyp\jxb300\ia32\node.lib` which links to `jx.dll` whereas `x64\node.lib` links to `jx.exe`.

**Comment by obastemur** [comment] 2015-05-24 21:56
@zamb3zi Thanks for the details. I couldn't reproduce it because I was also testing against x64. I'm replacing the node.lib for Win32.

**Comment by ktrzeciaknubisa** [comment] 2015-05-25 13:21
Should be fixed now. However current `%HOMEPATH%\.node-gyp\` should be removed manually before first `jx install` use.

**Closed by ktrzeciaknubisa** 2015-05-25 13:21 UTC

**Comment by ktrzeciaknubisa** [comment] 2015-05-25 14:00
@zamb3zi 

> If I install instead with npm install ffi then the resulting package works with both node and the installed version of jxcore

Which version of node/npm did you use for that? On my platform (npm 2.7.4 and node v0.10.38)  `npm install ref && node -p require('ref')` fails similarly as for you:

```bash
C:\jxcore\tmp\x359\node_modules\ref\node_modules\bindings\bindings.js:83
        throw e
              ^
Error: The specified procedure could not be found.
c:\jxcore\tmp\x359\node_modules\ref\build\release\binding.node
    at Object.process.dlopen [as .node] (node.js:692:25)
    at Module.load (module.js:346:36)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:378:17)
    at require (module.js:396:17)
    at bindings (C:\jxcore\tmp\x359\node_modules\ref\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (C:\jxcore\tmp\x359\node_modules\ref\lib\ref.js:5:47)
    at Module._compile (module.js:519:26)
    at Object.Module._extensions..js (module.js:549:10)
    at Module.load (module.js:346:36)
```

**Comment by ktrzeciaknubisa** [comment] 2015-05-25 14:17
@zamb3zi Please forget my previous question. I had some configuration issues. Once resolved, it works for npm.

**Comment by zamb3zi** [comment] 2015-05-25 15:17
Thank you both very much. I can confirm everything is working for me now on jxcore x86.

**Comment by zamb3zi** [comment] 2015-05-26 03:52
I have a question about this though. Right now, I'm running with `jx.exe` during this development phase, but I intend to switch to an embedded architecture later. Will it still be possible to use modules like `ref`/`ffi` via `jx.dll` if they've been linked against `jx.exe`? Perhaps `jx install` needs a configuration switch to choose dll/exe linkage?
