### ISSUE TITLE
(Plesk) Massive CPU load

### ISSUE THREAD

**Issue by purepear** [jxcore/jxcore#373] opened 2015-06-01 14:18 UTC
Our host support noticed that Node applications are using way too much CPU.
So i updated to the newest extension version 2.0.6 and jxcore 0.3.0.1 but the problem still exists.

CentOS Linux 7.1.1503 (Core)
Plesk 12.0.18 

this is a test app
```
var http = require('http')
http.createServer(function (req, res) {
    res.writeHead(200, {'Content-Type': 'text/html'});
    res.end("Test");
    console.log(new Date().toUTCString())
}).listen(11111, '127.0.0.1');
```

as soon as it is restarted(file change or restart through plesk extension panel) it starts using CPU like ~100%, ~200%, ~50%, ~250%, ~150%... and so on.. i use **top** command. This goes for every app that is running so you can imagine how bad this is.

I stopped the app in plesk and ran it with /usr/local/psa/var/modules/jxcore-support/jx_rh64v8/jx app.js and i believe the only CPU usage was when i made curl requests .. so i guess the problem is how plesk extension manages/runs the apps.

If you have ideas on how to test further just let me know. 

One other thing that i'm concerned is all apps are running with root user. Why not using the domain user at least for security reasons.

Anyone else with similar problem.. btw i didn't noticed this cpu usage until today so others may have the same issue but not be aware.

**Comment by ktrzeciaknubisa** [comment] 2015-06-01 14:40
We haven't seen this on out testing platforms. 

Can you verify exactly which process takes the CPU? (there may be multiple jx processes running even with just one app enabled).

> One other thing that i'm concerned is all apps are running with root user. 

They are not. They are spawned with user's gid/uid. Again, maybe you saw other process used by JXcore extension (not the user's app). Can you make sure by checking process pid?

**Comment by ktrzeciaknubisa** [comment] 2015-06-01 14:48
You can add `process.title = "myApp";` to your code, this should help you to identify the app on processes list.

**Comment by purepear** [comment] 2015-06-01 14:55
You are right.. my app itself is using the domain user and does not cause cpu problems.. however there is one other 'jx' that is ran just before my app is restarted.. i noticed it cause they have similar PIDs and when i stop the app it stops too... So every app started have root jx process that causes a lot of CPU usage

**Comment by obastemur** [comment] 2015-06-01 14:58
@ktrzeciaknubisa  Sounds like a sub monitoring process ?

**Comment by ktrzeciaknubisa** [comment] 2015-06-01 14:59
@obastemur more likely app's spawner. 

@purepear Can you identify the path of the problematic process, e.g. with `ps aux | grep jx` ?

**Comment by ktrzeciaknubisa** [comment] 2015-06-01 15:00
@purepear also, please take a look into app's log to see if it's not in circular restart state?

**Comment by purepear** [comment] 2015-06-01 15:07
```
root     7972   150  0.3 1322780 100740 ?      Rl   14:51  12:04 /usr/local/psa/var/modules/jxcore-support/subs_configs/mydomain.com/jx /usr/local/psa/var/modules/jxcore-support/spawner_5.jx -opt {"user":"myuser","home":"\/var\/www\/vhosts\/mydomain.com\/httpdocs\/","log":"jxcore_logs\/index.txt","file":"index.js","domain":"mydomain.com","tcp":"10018","tcps":"10019","logWebAccess":"0","args":[],"plesk":true,"nginx":true} respawn_id:1
myuser   8005   0.0  0.0 669332 15852 ?        Sl   14:51   0:00 myapp jx
root     19543  0.2  0.0 684436 28996 ?        Ssl  13:18   0:12 /usr/local/psa/var/modules/jxcore-support/jx_rh64v8/jx monitor startx
root     19550  0.7  0.1 2436120 41232 ?       Sl   13:18   0:45 ./jx monitor run /usr/local/psa/var/modules/jxcore-support/service.jx
```

1 - the CPU load problem
2 - myapp
3 and 4 i think are always up and running

I deleted the other processes but for every other app there are two processes like 1 and 2 and the 'root'  one uses a lot of cpu

**Comment by purepear** [comment] 2015-06-01 15:19
@ktrzeciaknubisa I looked at the log and it's not in circular restart state.

**Comment by ktrzeciaknubisa** [comment] 2015-06-01 15:23
@purepear Thanks. We have a suspect. Could you please check in `/opt/psa/var/modules/jxcore-support` folder if `spawner_5.jx` is a copy if `spawner.jx` (same file size, and even better: `shasum spawner*.jx`).

**Comment by purepear** [comment] 2015-06-01 15:33
```
5384589ec409e372f01c25c6345846d7e6b12aa5  spawner_2.jx
5384589ec409e372f01c25c6345846d7e6b12aa5  spawner_5.jx
5384589ec409e372f01c25c6345846d7e6b12aa5  spawner.jx
```
Looks like there are 3 identical files

**Comment by purepear** [comment] 2015-06-01 16:15
@ktrzeciaknubisa  btw the directory of these files is /usr/local/psa/var/modules/jxcore-support

**Comment by ktrzeciaknubisa** [comment] 2015-06-01 16:17
> btw the directory of these files is /usr/local/psa/var/modules/jxcore-support

I believe they are symlinked.

> Looks like there are 3 identical files

They are expected to be clones. Just wanted to check it. 

We should find out the reason, why they use so much CPU. In your app home dir (`var/www/vhosts/mydomain.com/httpdocs`) - are there any nested subfolders? The reason why I ask is that file watcher module is iterating through them to detect file changes (in case of large directory structure this might be one of the causes, although we never observed this on Ubuntu). If that's the case, could you try to have just app.js in a folder and see the difference?

**Comment by purepear** [comment] 2015-06-01 16:31
I made a test directory and put the app there /test/app.js and changed the path in plesk.
Now the problem root process is using 1%-2% cpu which is still a lot for watching just one file but at least we know what the bug is.
Btw before that i moved all the code in the parent directory and there were a git folder and uploads folder .. none of them have js files ... but cpu was like 20%-30%... so it looks like it is watching none js files too.
Maybe a solution would be to just use an empty 'restart' file... if touched/changed restart the app.
I think Phusion Passenger use this approach.

**Comment by ktrzeciaknubisa** [comment] 2015-06-01 16:45
We're using [chokidar](https://github.com/paulmillr/chokidar) module for fs watching. It was chosen due to increased stability and performance. However by default it scans entire app folder. We might need to add some configuration options for domain's panel in Plesk (e.g. folder list for watching/[excluding](https://github.com/jxcore/jxcore/issues/180) etc.).

Also the interval is default (100 ms I believe), so I wonder it this is responsible for 1-2% of CPU.

**Comment by ktrzeciaknubisa** [comment] 2015-06-01 16:49
> so it looks like it is watching none js files too

Well, our assumption was, that if you upload a js file into a folder, which does not contain js files yet - the restart will work, too. That's why the non-js folders are watched.

**Comment by purepear** [comment] 2015-06-01 17:02
I think watching all files is not the right choice cause even if you separate all non js files/directories... you still have node_modules which might contain A LOT OF files.. which could be ok for a server running single app but using plesk you probably want to host more apps ... and this adds up.

What do you think about an empty file touch to trigger the restart.. or at least an option in plesk panel to do so

**Comment by obastemur** [comment] 2015-06-01 17:05
AFAIK we had the watch depth defined 2. It shouldn't matter how many unrelated files are available under node_modules/module/sub folders. @ktrzeciaknubisa do we still have the same depth check?

**Comment by ktrzeciaknubisa** [comment] 2015-06-01 17:14
@obastemur Nope, we don't have the depth check since we switched to chokidar module (which on the other hand solved our multiple previous issues). However it look's like this module can be easily configured for depth value, which I didn't see before. We may add it easily.

**Comment by ktrzeciaknubisa** [comment] 2015-06-01 17:16
> What do you think about an empty file touch to trigger the restart..

Well, If we would add config for watched paths, and you would just enter "empty.file" there - it would work this way.

**Comment by purepear** [comment] 2015-06-01 17:17
> Well, If we would add config for watched paths, and you would just enter "empty.file" there - it would work this way.

Sounds good

**Comment by ktrzeciaknubisa** [comment] 2015-06-02 17:13
No worries, I've already optimized the watching part for doing as much as before, but without CPU effort. The next step will be to add some configurable options to domain's panel page. @purepear When it's ready, would you like to test it before publishing an update?

**Comment by purepear** [comment] 2015-06-03 04:17
@ktrzeciaknubisa sure

**Comment by purepear** [comment] 2015-06-16 14:44
@ktrzeciaknubisa When do you think the new version will be out.. cause the server is running a lot of CPU :)

**Comment by obastemur** [comment] 2015-06-16 14:46
@purepear We are preparing the release for tomorrow. @ktrzeciaknubisa this will be included right?

**Comment by ktrzeciaknubisa** [comment] 2015-06-16 14:54
I guess @purepear is asking for new Plesk's extension. Will not be ready tomorrow, still needs finishing up and more tests. Tomorrow we're planning to release jx 3.0.3 binaries.

**Comment by ktrzeciaknubisa** [comment] 2015-06-16 14:58
@purepear There is a chance to have unnofficial Plesk extension update next week, so you can test it out.

**Comment by purepear** [comment] 2015-06-30 10:32
@ktrzeciaknubisa any news on the new version? :)

**Comment by ktrzeciaknubisa** [comment] 2015-06-30 10:44
It's still on the way, although it needs a little bit more time. Except for the reducing CPU load we're also applying stability for app monitoring tool which needs some attention and lots of internal tests. I do remember, that you wait for the update :)

**Comment by ktrzeciaknubisa** [comment] 2015-07-03 20:46
We're very close after 51b90d2696056ce0ca1b3abe6a08d01f3a3a696a monitoring tool improvements. My estimation is that the latest on Tuesday I'll have a beta version for you. Or Monday if everything goes smooth.

**Comment by purepear** [comment] 2015-07-04 10:31
Great :)

**Comment by ktrzeciaknubisa** [comment] 2015-07-07 18:55
Ok, you can take it from [here](https://github.com/ktrzeciaknubisa/jxcore-issues/raw/master/plesk/dev/JXcore_Plesk.zip). Please remember, this is development version. However it is tested and working, I gave my best to it.

The domain's panel contains new tab dedicated to Restart Manager. It should reduce CPU usage with default values (without submitting domain's form).
 
Please let me know of any your thoughts/opinions.

**Comment by purepear** [comment] 2015-07-08 11:54
Thanks so much
Installed it already.. so far so good :)

**Comment by ktrzeciaknubisa** [comment] 2015-08-12 09:21
The JXcore 0.2.7 extension for Plesk is now officially [published](https://ext.plesk.com/packages/28f799af-1ff4-4bb8-9c87-a04f0f23d32e-jxcore-support). After the installation, it is recommended to upgrade JXcore to 0.3.0.5.

We have gathered the most important changes and put them into our blog post: [More features in JXcore Plesk Extension v0.2.7](http://jxcore.com/more-features-in-jxcore-plesk-extension-v0-2-7/).

**Closed by ktrzeciaknubisa** 2015-08-12 09:21 UTC
