### ISSUE TITLE
JXcore Plesk Extension for Node won't start

### ISSUE THREAD

**Issue by dottodot** [jxcore/jxcore#758] opened 2016-01-04 11:57 UTC
I've had to restart my server and now I can't get the JXcore Plesk Extension to start monitoring and not seeing any error so completely stuck as what to do

**Comment by obastemur** [comment] 2016-01-04 12:00
did you check the monitor log file ?

**Comment by dottodot** [comment] 2016-01-04 12:01
Is that in /var/log ?

**Comment by ktrzeciaknubisa** [comment] 2016-01-04 12:03
@dottodot  See log files under */opt/psa/var/modules/jxcore-support/jxcore* . What happens when you click `Start` on *JXcore Configuration* tab?

**Comment by dottodot** [comment] 2016-01-04 12:11
When I restart it starts showing the loading icon then after about 1min it just returns to the previous state with the option to start it.

These are the log files I can see
jxcore.monitor.console.log
jx_monitor_41_201-1444375081481.log
jx_monitor_41_201-1444839510737.log
jx_monitor_41_201-1444840141710.log
jx_monitor_41_201-1444843613467.log
jx_monitor_41_201-1444845001631.log

But there is no date or time next to the contents so not sure when they were logged 

jxcore.monitor.console.log just contains JXcore monitoring is started.

**Comment by obastemur** [comment] 2016-01-04 12:13
simple `ls -l` would show you file system creation time

**Comment by ktrzeciaknubisa** [comment] 2016-01-04 12:15
Now I see this behavior on Ubuntu x32, but I doesn't occur on x64. @dottodot which is your platform?

**Comment by dottodot** [comment] 2016-01-04 12:18
Sorry not with it today. Here's some of the content from todays log file, it looks like it the same thing over and over so not posted it all.

My platform is 	‪CentOS 6.7 x64
```
Parameter 'monitor.host' is not present in jx.config. Using default value: '127.0.0.1'.
Parameter 'monitor.port' is not present in jx.config. Using default value: '17777'.
Parameter 'monitor.check_interval' is not present in jx.config. Using default value: '1000'.
Parameter 'monitor.start_delay' is not present in jx.config. Using default value: '2000'.
Using log_path: /usr/local/psa/var/modules/jxcore-support/jxcore/jx_monitor_41_201-1444845001631.log
JXcore monitoring is started.
Monitor started on https://127.0.0.1:17777
Monitor received request: /jx_who_are_you
Monitor received request: /jx_who_are_you
Monitor received request: /sending_data
Received data from process. {"pid":22332,"path":"/usr/local/psa/var/modules/jxcore-support/spawner_3.jx","argv":["/usr/local/psa/var/modules/jxcore-support/subs_configs/the-plug.com/jx","/usr/local/psa/var/modules/jxcore-support/spawner_3.jx","-opt","{\"user\":\"plug\",\"home\":\$
Monitor received request: /sending_data
Received data from process. {"pid":22329,"path":"/usr/local/psa/var/modules/jxcore-support/service.jx","argv":["/usr/local/psa/var/modules/jxcore-support/jxcore/jx","monitor","run","/usr/local/psa/var/modules/jxcore-support/service.jx"],"config":null,"threadIDs":[-1]}
Respawned process. Old pid : 22332 with args ["/usr/local/psa/var/modules/jxcore-support/subs_configs/the-plug.com/jx","/usr/local/psa/var/modules/jxcore-support/spawner_3.jx","-opt","{\"user\":\"plug\",\"home\":\"\\/var\\/www\\/vhosts\\/the-plug.com\\/httpdocs\\/newdatabase\\/se$
Monitor received request: /jx_who_are_you
Monitor received request: /jx_who_are_you
Monitor received request: /sending_data
Received data from process. {"pid":22351,"path":"/usr/local/psa/var/modules/jxcore-support/spawner_11.jx","argv":["/usr/local/psa/var/modules/jxcore-support/subs_configs/clubsandspades.co.uk/jx","/usr/local/psa/var/modules/jxcore-support/spawner_11.jx","-opt","{\"user\":\"clubsan$
Monitor received request: /sending_data
Found app with the old PID: 22332
Received data from process. {"pid":22353,"path":"/usr/local/psa/var/modules/jxcore-support/spawner_3.jx","argv":["/usr/local/psa/var/modules/jxcore-support/subs_configs/the-plug.com/jx","/usr/local/psa/var/modules/jxcore-support/spawner_3.jx","-opt","{\"user\":\"plug\",\"home\":\$
Respawned process. Old pid : 22351 with args ["/usr/local/psa/var/modules/jxcore-support/subs_configs/clubsandspades.co.uk/jx","/usr/local/psa/var/modules/jxcore-support/spawner_11.jx","-opt","{\"user\":\"clubsandspades\",\"home\":\"\\/var\\/www\\/vhosts\\/clubsandspades.co.uk\\/$
Monitor received request: /jx_who_are_you
Monitor received request: /jx_who_are_you
Monitor received request: /sending_data
Received data from process. {"pid":22389,"path":"/usr/local/psa/var/modules/jxcore-support/spawner_23.jx","argv":["/usr/local/psa/var/modules/jxcore-support/subs_configs/hot-soles.com/jx","/usr/local/psa/var/modules/jxcore-support/spawner_23.jx","-opt","{\"user\":\"hot-soles\",\"$
Monitor received request: /sending_data
Found app with the old PID: 22351
Received data from process. {"pid":22391,"path":"/usr/local/psa/var/modules/jxcore-support/spawner_11.jx","argv":["/usr/local/psa/var/modules/jxcore-support/subs_configs/clubsandspades.co.uk/jx","/usr/local/psa/var/modules/jxcore-support/spawner_11.jx","-opt","{\"user\":\"clubsan$
Respawned process. Old pid : 22389 with args ["/usr/local/psa/var/modules/jxcore-support/subs_configs/hot-soles.com/jx","/usr/local/psa/var/modules/jxcore-support/spawner_23.jx","-opt","{\"user\":\"hot-soles\",\"home\":\"\\/var\\/www\\/vhosts\\/hot-soles.com\\/httpdocs\\/new\\/\"$
Monitor received request: /jx_who_are_you
Monitor received request: /jx_who_are_you
Monitor received request: /sending_data
Received data from process. {"pid":22450,"path":"/usr/local/psa/var/modules/jxcore-support/spawner_37.jx","argv":["/usr/local/psa/var/modules/jxcore-support/subs_configs/the-plug.com/jx","/usr/local/psa/var/modules/jxcore-support/spawner_37.jx","-opt","{\"user\":\"plug\",\"home\"$
Monitor received request: /sending_data
Found app with the old PID: 22389
Received data from process. {"pid":22452,"path":"/usr/local/psa/var/modules/jxcore-support/spawner_23.jx","argv":["/usr/local/psa/var/modules/jxcore-support/subs_configs/hot-soles.com/jx","/usr/local/psa/var/modules/jxcore-support/spawner_23.jx","-opt","{\"user\":\"hot-soles\",\"$
Respawned process. Old pid : 22450 with args ["/usr/local/psa/var/modules/jxcore-support/subs_configs/the-plug.com/jx","/usr/local/psa/var/modules/jxcore-support/spawner_37.jx","-opt","{\"user\":\"plug\",\"home\":\"\\/var\\/www\\/vhosts\\/the-plug.com\\/httpdocs\\/etiksync\\/\",\$
Monitor received request: /jx_who_are_you
Monitor received request: /jx_who_are_you
Respawned process. Old pid : 22391 with args ["/usr/local/psa/var/modules/jxcore-support/subs_configs/clubsandspades.co.uk/jx","/usr/local/psa/var/modules/jxcore-support/spawner_11.jx","-opt","{\"user\":\"clubsandspades\",\"home\":\"\\/var\\/www\\/vhosts\\/clubsandspades.co.uk\\/$
Monitor received request: /jx_who_are_you
Monitor received request: /sending_data
Received data from process. {"pid":22489,"path":"/usr/local/psa/var/modules/jxcore-support/spawner_38.jx","argv":["/usr/local/psa/var/modules/jxcore-support/subs_configs/clubsandspades.co.uk/jx","/usr/local/psa/var/modules/jxcore-support/spawner_38.jx","-opt","{\"user\":\"clubsan$
Monitor received request: /sending_data
Found app with the old PID: 22450
```

**Comment by ktrzeciaknubisa** [comment] 2016-01-04 12:21
@dottodot Yes, looks like in this case log file is not created. I removed all old logs and the new one did not appeared. Give me few secs to find out what's going on.

BTW. which JXcore version are you using?

**Comment by dottodot** [comment] 2016-01-04 12:23
Jxcore v0.3.1.0 and the extension is 0.2.8

**Comment by ktrzeciaknubisa** [comment] 2016-01-04 12:53
Thanks. Unfortunately I don't reproduce the problem any more. The issue on my side was related to incorrect system date of Ubuntu VM, and so the cron task responsible for launching monitoring service could not get executed. I fixed that by rebooting the platform and auto-syncing the date.

@dottodot You said, that you did also reboot. Do you remember if the monitor service started successfully right after you made an upgrade of JXcore to 0.3.1.0 (I never saw a problem there)? And now you just cannot make it run after reboot?

**Comment by dottodot** [comment] 2016-01-04 13:02
After I'd done the reboot I'd noticed it wasn't running, and after several attempt to start it I decided to update it to the latest version to see if that would help.

Does the entries in the log file mentioning `Found app with the old PID` have anything to do with it?

**Comment by ktrzeciaknubisa** [comment] 2016-01-04 13:10
Nope, `Found app with the old PID` refers to particular apps (running under domains) being restarted. 

Do you have sudo access? When you execute `crontab -u root -l` command you should have an entry:

> @reboot /opt/psa/var/modules/jxcore-support/jxcore-for-plesk-startup.sh

For some reason this batch failed or was not called on restart. 

However if that's critical case, you may run it manually with sudo to see if that starts. And when it does, you will see monitoring tool running on JXcore extension pages.

**Comment by dottodot** [comment] 2016-01-04 13:17
Ok manually running the script has got it up and running so that's good. There were a few of the following error, but not exactly sure what there are referring to

```
Your package was created with older JXcore packaging format which is currently depreciated and its support will be removed in future JXcore releases.
Don`t worry, for the moment the package can still be executed.
However we recommend recreating a package using the latest JXcore version (also for better performance).
```

**Comment by ktrzeciaknubisa** [comment] 2016-01-04 13:22
That's only a warning, nothing serious. We have changed packaging algorithm in JXcore 0.3.1.0, and so service packages used by JXcore Extension 0.2.8 still uses previous format, which is also supported for now.

Now when you have it running I bet the problem will come back once you press `Stop` and `Start`, so the issue is still not resolved. How about a new, fresher restart? (is @reboot entry present in crontab?)

**Comment by dottodot** [comment] 2016-01-04 13:25
No @reboot isn't in the crontab, can I add this manually?

**Comment by ktrzeciaknubisa** [comment] 2016-01-04 13:29
That's interesting. Is there any other jxcore related entry? For example, when you press `Start` new entry should be added, e.g.:

```bash
##JXcore-immediate-Begin
19 12 4 1 * /opt/psa/var/modules/jxcore-support/jxcore-for-plesk-startup.sh
#JXcore-immediate-End
```

If it is not there, than it means that crontab does not get updated by extension...

**Comment by dottodot** [comment] 2016-01-04 13:33
This is my full crontab
```
0	1	*	*	1	/usr/local/psa/libexec/modules/watchdog/cp/send-report weekly
10	1	*	*	*	/usr/local/psa/libexec/modules/watchdog/cp/clean-sysstats
##JXcore-immediate-End
0	4	*	*	*	/home/backup/mysql-d7plugbackup.sh
15	1	*	*	1	/usr/local/psa/libexec/modules/watchdog/cp/pack-sysstats week
30	4	*	*	*	/home/backup/mysql-d7databasebackup.sh
30	3	*	*	*	/home/backup/mongo-backup.sh
15	1	*	*	*	/usr/local/psa/libexec/modules/watchdog/cp/pack-sysstats day
##JXcore-Begin
30	5	*	*	sun	/home/backup/drupal7-backup.sh
30	6	*	*	*	/home/backup/mysql-backup.sh
15	1	1	*	*	/usr/local/psa/libexec/modules/watchdog/cp/pack-sysstats month
29	17	14	10	*	/usr/local/psa/var/modules/jxcore-support/jxcore-for-plesk-startup.sh
##JXcore-immediate-Begin
0	1	*	*	1	/usr/local/psa/libexec/modules/watchdog/cp/secur-check
15	1	1	*	*	/usr/local/psa/libexec/modules/watchdog/cp/pack-sysstats year
50	18	14	10	*	/usr/local/psa/var/modules/jxcore-support/jxcore-for-plesk-startup.sh
MAILTO=""
0,10,20,30,40,50	*	*	*	*	/usr/local/psa/admin/bin/php -dauto_prepend_file=sdk.php '/usr/local/psa/admin/plib/modules/plesk-mobile/scripts/push_worker.php'
47	23	*	*	*	/usr/sbin/ntpdate -b -s 0.uk.pool.ntp.org
```

**Comment by ktrzeciaknubisa** [comment] 2016-01-04 13:38
It got broke! 

Please remove:

* both `/usr/local/psa/var/modules/jxcore-support/jxcore-for-plesk-startup.sh` entries
* all `##JXcore-immediate-End`, `##JXcore-Begin`, `##JXcore-immediate-Begin` comments

After that click `Reinstall` on *JXcore Configuration* tab and it should be fixed.

**Comment by dottodot** [comment] 2016-01-04 14:01
Yes that's fixed it. Many thanks for your help.

**Comment by ktrzeciaknubisa** [comment] 2016-01-04 14:02
Did you check if all works after reboot? Also with manual `Stop` / `Start` ?

**Comment by dottodot** [comment] 2016-01-04 14:03
Not yet as don't want to reboot the server at this point but stop start works.

**Comment by ktrzeciaknubisa** [comment] 2016-01-04 14:05
Ok, that's promising. I'm going to add some validation of crontab file to next JXcore extension release, so this kind of issues hopefully will not appear any more. Thank you for your cooperation :)

**Closed by ktrzeciaknubisa** 2016-01-04 14:05 UTC
