### ISSUE TITLE
Segfault (asm.js + spidermonkey)

### ISSUE THREAD

**Issue by bondneverdies** [jxcore/jxcore#624] opened 2015-10-28 13:23 UTC
It seems that there is a problem while running some asm.js code with the spider monkey engine. This does not appear using the v8 engine or directly running the code in firefox.

Here are the steps to reproduce the problem:

First paste the following C code in a file (compute the 45th fibonacci number)

     #include <stdio.h>
      
     int fib(int x) {
       if (x < 2) {
         return 1;
       } else {
         return fib(x - 1) + fib(x - 2);
       }
     }
     
     int main() {
       int result = fib(45);
     
       printf("%d\n", result);
       return 1;
     }

Then compile to in asm.js with emscripten:

      $ emcc -O1 -s ASM_JS=1 ./fibonacci.cpp

Finally try run it with jxcore, compiled with SpiderMonkey (`$ curl http://jxcore.com/xil.sh | bash -s force sm`). This will result in a segfault

      $ jx a.out.js
      Segmentation fault (core dumped)

Additional infos:

      $ jx -jsv
      Mozilla SpiderMonkey v34
      $ jx -jxv
      v 0.3.0.7
      $ uname -a 
      Linux user-pc 3.13.0-66-generic #108-Ubuntu SMP Wed Oct 7 15:20:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ktrzeciaknubisa** [comment] 2015-10-30 16:13
Right. I see it on Ubuntu too. However same code executed on OSX or Windows says:

```bash
TypeError: anonymous is not a scripted function (module.js 567:20)
    at Module.prototype._compile (module.js:567:21)
    at Module._extensions[".js"] (module.js:627:1)
    at Module.prototype.load (module.js:418:1)
    at Module._load (module.js:382:1)
    at Module.runMain (module.js:818:1)
    at startup (node.js:374:1)
    at node.js:1468:1
```

As a side note, I was amazed how this simple c++ code (210 bytes) got converted into 365 kB (well, including comments :)

Anyway I gave it also a try with [jx compiled for Google V8 v3.28.71.19](https://github.com/jxcore/jxcore/blob/0.3.1.0/doc/HOW_TO_COMPILE.md#v8-328) and it worked on OSX: 

```bash
$ jx a.out.js 
1836311903
```

It might work on your platform too.

**Comment by bondneverdies** [comment] 2015-10-31 09:50
You are right, I forgot to mention that It's working for me when jxcore is compiled with v8, that's why I wrote "spidermonkey" in the title.

Do you think this is more like an emscripten issue ?

**Comment by obastemur** [comment] 2015-10-31 10:39
Looks like a bug to me. Can anyone post the GDB output here;

```
gdb jx
run theapp.js
```

**Comment by ktrzeciaknubisa** [comment] 2015-11-02 09:52
This is what I get:

```bash
(gdb) run a.out.js
Starting program: /usr/local/bin/jx a.out.js
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x000000000091ca6d in bool js::XDRScript<(js::XDRMode)0>(js::XDRState<(js::XDRMode)0>*, JS::Handle<JSObject*>, JS::Handle<JSScript*>, JS::Handle<JSFunction*>, JS::MutableHandle<JSScript*>) ()
```

**Comment by dominictarr** [comment] 2015-12-06 04:44
I am also getting this error when trying to run https://www.npmjs.com/package/libsodium-wrappers on jsx with spidermonkey

**Comment by obastemur** [comment] 2015-12-15 02:19
@bondneverdies @dominictarr @ktrzeciaknubisa thanks for all the details. This should be fixed with 0.3.1.0 release

**Closed** 2015-12-15 02:18 UTC

**Comment by dominictarr** [comment] 2015-12-16 01:52
when well 0.3.1.0 be released? the install script detects that I have the latest version at 0.3.0.7

**Comment by dominictarr** [comment] 2015-12-16 01:55
it looks like the problem is that
https://github.com/jxcore/jxcore/blob/master/tools/jx_install.sh#L132
gets a response that still says 0.3.0.7 is current

the response was:
```
https://jxcore.s3.amazonaws.com/0307|0.3.0.7
```

**Comment by ktrzeciaknubisa** [comment] 2015-12-16 08:30
Yeap, 0.3.1.0 is not released yet, thus 0.3.0.7 is currently the latest.

**Comment by dominictarr** [comment] 2015-12-16 22:14
@ktrzeciaknubisa when will it be released? or is there a way I can install via git?

**Comment by bondneverdies** [comment] 2015-12-17 08:40
You can build jxcore from the sources, [the instructions are provided here](https://github.com/jxcore/jxcore/blob/master/doc/HOW_TO_COMPILE.md)

**Comment by dominictarr** [comment] 2015-12-17 23:19
@bondneverdies  thanks, i'm gonna try that. when will 0.3.1.0 be released?

**Comment by dominictarr** [comment] 2015-12-18 01:30
cool, that works - confirmed fixed.

**Comment by obastemur** [comment] 2015-12-18 05:22
@dominictarr Thanks for confirming the fix. We release it today
