### ISSUE TITLE
Unable to add npm module bcrypt on JXCore Plesk Extension

### ISSUE THREAD

**Issue by gopumon** [jxcore/jxcore#756] opened 2016-01-03 21:31 UTC
When I tried add `bcrypt` to NPM modules.
It failed with error as in the log
````````````
246 info install bcrypt@0.8.5
247 verbose unsafe-perm in lifecycle false
248 info bcrypt@0.8.5 Failed to exec install script
249 info /usr/local/psa/var/modules/jxcore-support/native_modules/node_modules/bcrypt unbuild
250 info preuninstall bcrypt@0.8.5
251 info uninstall bcrypt@0.8.5
252 verbose true,/usr/local/psa/var/modules/jxcore-support/native_modules/node_modules,/usr/local/psa/var/modules/jxcore-support/native_modules/node_modules unbuild bcrypt@0.8.5
253 info postuninstall bcrypt@0.8.5
254 error bcrypt@0.8.5 install: `node-gyp rebuild`
254 error Exit status 1
255 error Failed at the bcrypt@0.8.5 install script.
255 error This is most likely a problem with the bcrypt package,
255 error not with npm itself.
255 error Tell the author that this fails on your system:
255 error node-gyp rebuild
255 error You can get their info via:
255 error npm owner ls bcrypt
255 error There is likely additional logging output above.
256 error System Linux 2.6.32-042stab111.12
257 error command "/usr/local/psa/var/modules/jxcore-support/jxcore/jx" "/usr/local/psa/var/modules/jxcore-support/jxcore/.jx/npm" "install" "--loglevel" "http" "--color" "true" "bcrypt" "--no-bin-links" "--build-from-source"
258 error cwd /usr/local/psa/var/modules/jxcore-support/native_modules
259 error node -v v0.10.40
260 error npm -v 1.4.14
261 error code ELIFECYCLE
262 verbose exit [ 1, true ]

jx install bcrypt
````````````
but works in node installations with `npm install bcrypt`.

**Comment by gopumon** [comment] 2016-01-03 21:55
I think upgrading node from v0.10.40 to v4.1.2 or v5.3.0 in the JXCore will solve this issue as said in [NodeJS 4 & 5 npm install fail for bcrypt and db-migrate](http://stackoverflow.com/questions/33532528/nodejs-4-5-npm-install-fail-for-bcrypt-and-db-migrate)

**Comment by ktrzeciaknubisa** [comment] 2016-01-04 10:59
Thanks @gopumon . I see the problem when I try to install `bcrypt` through JXcore extension too. What's interesting is that `jx install bcrypt` works on same machine from the command line. I'll check it out.

**Comment by ktrzeciaknubisa** [comment] 2016-01-05 18:52
Hi @gopumon . The issue is fixed now with above commit, but you need either to wait for next JXcore release or build 0.3.1.1 branch by yourself (and then replace it for Plesk). Or if your Plesk platform is ub64, then I can provide you with compiled binary I made for testing the fix.

**Closed** 2016-01-08 17:16 UTC
