### ISSUE TITLE
Tasks and multiple JSON serialization

### ISSUE THREAD

**Issue by Bowser** [jxcore/jxcore#252] opened 2015-03-23 10:07 UTC
Hi,
I understood from the code of
https://github.com/jxcore/jxcore/blob/2a2084fe74b00e4fe921a9a7eea5a533615a632b/lib/jx/_jx_tasks.js
https://github.com/jxcore/jxcore/blob/2a2084fe74b00e4fe921a9a7eea5a533615a632b/src/node.js

that actually JXcore does already a JSON serialization (stringify/parse) of thread messages/tasks parameters.
I have a string, actually a JSON string don't even parsed, that I must send to a specified thread. I state that in my architecture different threads load different libraries of my app, and I send them tasks depending on what user requested; this because I don't want to have too much memory allocated by libraries (having all of them loading all the libraries).

I need to have this string read into the main thread (or even into a generic task of an undefined thread) and then understand what particular thread can handle it (i'm doing a simple substr to get it) and send to it (runOnThread)

Because I don't have any advantage to parse it at the beginning (then stringify and reparse again wasting overhead), It will be great to send it to the thread and have it already parsed when I receive it (because jxcore already use JSON). Instead I noticed that currently it returns me again a string when i get it into a task of the thread, after having worked it with JSON)

Is this possible in the current release of JX or perhaps it will be for one of the following version, recognizing himself that it handles a JSON parameter or maybe with an additional parameter that specify what we want (or directly manipulating the behavior of jx from my code with internal methods)?

**Comment by ktrzeciaknubisa** [comment] 2015-03-23 10:19
Hi @Bowser . Let me know if I understand this right: you have a string, which is a json already stringified and you want to send it without stringifying it again (by jxcore), but still to parse it by jxcore on receive?

**Comment by Bowser** [comment] 2015-03-23 10:25
Exactly, I would like to take advantage of the fact that JX does already it's own JSON parsing, without have to repeat the parse again

**Comment by ktrzeciaknubisa** [comment] 2015-03-23 10:59
@Bowser : apart from reparsing overhead, did you run some benchmarks to check, if this affects the performance in a visible way?

***

If we ever decide to introduce something like you propose, I see 2 options at the moment. It could be done by enabling/disabling of message stringifying/parsing on both ends (send/receive):

1. **globally**

    Some global options like:
    
    ```js
    jxcore.tasks.messageOptions = {
       stringifySend : false,  // default true
       parseReceive : true;  // default true
    };
```
   Those options could even be definable per thread, so e.g. once we would define them for the thread X, they would apply to all messages send by thread X and received from thread X. 

2. **per message**

    More flexible, however this would probably impact the performance, since those options would have to be added to the message string in some way (flags, bits or whatever), and each string would need to be checked for their presence. Then still any global variable would be useful, like `checkMessageOptions = true/false` (default `false` to keep the current behavior).

   At the same time also we could implement support for binary strings (an extra option), as for now jxcore does not support it.

What do you guys think of it? @obastemur ?

**Comment by Bowser** [comment] 2015-03-23 12:51
@ktrzeciaknubisa I didn't. I'm still redesigning my app since I've just landed in JX from a single-threaded Node environment. Surely this shouldn't be a bottleneck, since JSON performance are not so bad even with medium-size objects. I noticed just the meaningless of a double JSON parsing and wanted to figure out what was better to do.
----------------------

I don't understand why is needed an option for stringify. Couldn't be enough a type checking?
If we have a string, send it directly (since I understood it's mandatory to send data between threads as text, otherwise there shouldn't be any JSON processing). Only if we have an object, serialize it before.

On the other side, depending on what user decided (parseReceive true or false) JX would "save" the message as an object to parse (instead of a string).

```javascript
obj = ( typeof(params) === 'string' && parseReceive) ? '"'+params+'"' : JSON.stringify(params);
message = '{"threadId": ' + process.threadId + ', "params": ' + ( parseReceive ? obj : '"'+obj+'"' ) + '}';
tw.sendToAll( Y , message , X );
```

So, for example, if parseReceive is false we will have this JSON string as a message:
`'{"threadId": (process.threadId), "params": "(obj)"}'`
and after a JSON.parse, params will return a string.
Instead if parseReceive is true:
`'{"threadId": (process.threadId), "params": (obj)}'`
then JSON.parse will parse the object and return us what we need.

Obviously this way we need parseReceive be **true** as default, otherwise normal object sent with JX will return text. Of course this way the default behavior changes for someone (who like me send JSON as a text), but in reality I think that most of apps that send JSON string to another thread, have to parse that JSON anymore when arrives and this way we take advantage of an unique parsing.

**Comment by Bowser** [comment] 2015-03-23 12:52
@ktrzeciaknubisa I didn't. I'm still redesigning my app since I've just landed in JX from a single-threaded Node environment. Surely this shouldn't be a bottleneck, since JSON performance are not so bad even with medium-size objects. I noticed just the meaningless of a double JSON parsing and wanted to figure out what was better to do.
----------------------

I don't understand why is needed an option for stringify. Couldn't be enough a type checking?
If we have a string, send it directly (since I understood it's mandatory to send data between threads as text, otherwise there shouldn't be any JSON processing). Only if we have an object, serialize it before.

On the other side, depending on what user decided (parseReceive true or false) JX would "save" the message as an object to parse (instead of a string).

```javascript
obj = ( typeof(params) === 'string' && parseReceive) ? '"'+params+'"' : JSON.stringify(params);
message = '{"threadId": ' + process.threadId + ', "params": ' + ( parseReceive ? obj : '"'+obj+'"' ) + '}';
tw.sendToAll( Y , message , X );
```

So, for example, if parseReceive is false we will have this JSON string as a message:
`'{"threadId": (process.threadId), "params": "(obj)"}'`
and after a JSON.parse, params will return a string.
Instead if parseReceive is true:
`'{"threadId": (process.threadId), "params": (obj)}'`
then JSON.parse will parse the object and return us what we need.

Obviously this way we need parseReceive be **true** as default, otherwise normal object sent with JX will return text. Of course this way the default behavior changes for someone (who like me send JSON as a text), but in reality I think that most of apps that send JSON string to another thread, have to parse that JSON anymore when arrives and this way we take advantage of an unique parsing.

**Comment by ktrzeciaknubisa** [comment] 2015-03-23 13:17
> I don't understand the need of an option for stringify. Couldn't be enough a type checking?

Type checking on send would work, however on receive - it is always a string, but is this a stringified json or a regular string? We don't know, unless we don't mark it somehow. `JSON.parse()` fails for unstringified string.

> On the other side, depending on what user decided (parseReceive true or false) JX would "save" the message as an object to parse (instead of a string) when it arrives.

Well, I thought that the goal is to avoid unnecessary stringifying/parsing for the performance sake, while wrapping a message into `'{"threadId": (process.threadId), "params": "(obj)"}'` would not bring any benefit.

However, my apologies: I should have mentioned, that parse options would apply only to string messages, while all other objects would be stringified as well. Once you try to send stringified json it **is** a string and the options could apply in that case.

**Comment by obastemur** [comment] 2015-03-23 17:05
If there is a scenario that consumes significant time on wrapping-unwrapping parameters; I see two possible options for now;
a ) use shared memory store for data sharing among the threads
b ) use built-in sqlite memory db

Any other suggestion ?

Unfortunately we are restricted with V8's multi-thread limitations. We could do share much more among the threads if we were only supporting SpiderMonkey backend but it's not a case.

**Comment by Bowser** [comment] 2015-03-23 18:35
Sure it's absurd to have threads that don't have opportunity to share memory.
I hope that future releases of V8 or JXCore will give us better ways to use threads.

However, what do you think about my last suggestion?

**Comment by obastemur** [comment] 2015-03-24 17:11
Sounds good. Can you create a new Github issue with this feature request?

BTW; I was going to introduce shared ArrayBuffer but didn't. The problem is, when you offer something shared there you need the locks. We don't want to bring locks into JS.

**Comment by Bowser** [comment] 2015-03-25 00:06
I thought to roll up my sleeves and try to make the commit of this feature by myself.

I think I've done a good work, even if I did just some quick test of the results for today.
https://github.com/Bowser/jxcore/commit/77f30c85daec762de921fa546e9acc6f614d2d68
https://github.com/Bowser/jxcore/commit/ee50337eaba489e1c870788f5afc9203b7d1c6d0

If is it ok, I can open directly a pull request.

**Comment by obastemur** [comment] 2015-03-25 16:00
@Bowser this way you are able to send string right? How about checking the type of param and if it's string not stringify again? @ktrzeciaknubisa do we have any scenario might fail with my proposition ?

**Comment by Bowser** [comment] 2015-03-25 16:46
You are able to send string normally, using traditional methods without underscore prefix, instead if you use new exposed methods with underscore prefix, passing as a param an already stringified JSON, when it passes through JSON.parse, it's converted into a normal object (like if you passed an object using traditional methods).

Type checking is not a good choice as @ktrzeciaknubisa said before:
> Type checking on send would work, however on receive - it is always a string, but is this a stringified json or a regular string? We don't know, unless we don't mark it somehow.  JSON.parse()  fails for unstringified string.

**Comment by obastemur** [comment] 2015-03-25 17:07
Okay both looks and sounds good to me. please send a pull request. 
Thanks!

**Comment by ktrzeciaknubisa** [comment] 2015-05-19 15:10
I'm closing this subject as it was finalized with a [pull request 258.](https://github.com/jxcore/jxcore/pull/258).

**Closed by ktrzeciaknubisa** 2015-05-19 15:10 UTC
