### ISSUE TITLE
jxcore.store is not thread safe?

### ISSUE THREAD

**Issue by fatihpolatli** [jxcore/jxcore#747] opened 2015-12-25 09:43 UTC
hi,

i wrote a code with 30 thread, every thread have a variable inside it called "collectionName". i pass parameter for that name and store it inside jxcore.store. however it is not thread safe, collectionName variables confusing after a while. what is the trick about thread safe variables? below is my thread creation code

    function initThreads(globals) {

    for (var i = 0; i < 30; i++) {

        var method = function(params) {
            try {
                console.log("AreportDataNew_" + params.countData);
                console.log("LEN", params.countData, params.glob.dataService.allUsers.length);
                var BatchModule = require('../reportBatch/reportAccessLevelBatch2jx.js');

                var t = new BatchModule();

                t.setCollectionName("AreportDataNew_" + params.countData);
                t.setDataService(params.glob.dataService);
                // t.initialize();
            } catch (e) {
                console.log("MYCATCH");
                console.log(e);
            }

            return process.threadId;
        };

        jxcore.tasks.addTask(method, {
            countData: i,
            glob: globals
        }, function(err, result) {
            // this block of code executes back in the main thread,
            // after method() completes.
            console.log("This is result from subthreaded method:", result);
        });
    }
    }

this is trace output i wrote 20 seconds after thread creation completed. first one param i pass, and second one last value of collectionName variable inside every thread

	AreportDataNew_0  /  AreportDataNew_0
	AreportDataNew_1  /  AreportDataNew_20
	AreportDataNew_2  /  AreportDataNew_29
	AreportDataNew_3  /  AreportDataNew_14
	AreportDataNew_4  /  AreportDataNew_24
	AreportDataNew_5  /  AreportDataNew_5
	AreportDataNew_6  /  AreportDataNew_26
	AreportDataNew_7  /  AreportDataNew_7
	AreportDataNew_8  /  AreportDataNew_8
	AreportDataNew_9  /  AreportDataNew_17
	AreportDataNew_10  /  AreportDataNew_28
	AreportDataNew_12  /  AreportDataNew_17
	AreportDataNew_11  /  AreportDataNew_16
	AreportDataNew_14  /  AreportDataNew_14
	AreportDataNew_13  /  AreportDataNew_23
	AreportDataNew_15  /  AreportDataNew_29
	AreportDataNew_16  /  AreportDataNew_16
	AreportDataNew_17  /  AreportDataNew_17
	AreportDataNew_18  /  AreportDataNew_18
	AreportDataNew_20  /  AreportDataNew_20
	AreportDataNew_19  /  AreportDataNew_19
	AreportDataNew_22  /  AreportDataNew_26
	AreportDataNew_21  /  AreportDataNew_25
	AreportDataNew_23  /  AreportDataNew_23
	AreportDataNew_24  /  AreportDataNew_24
	AreportDataNew_25  /  AreportDataNew_25
	AreportDataNew_26  /  AreportDataNew_26
	AreportDataNew_28  /  AreportDataNew_28
	AreportDataNew_27  /  AreportDataNew_27
	AreportDataNew_29  /  AreportDataNew_29

**Comment by obastemur** [comment] 2015-12-26 20:51
@fatihpolatli The problem is not understandable from the code you have shared. One trick, do not define a function inside a loop. 

Could you please try to explain the problem with an actual usage of jxcore.store ?

**Comment by fatihpolatli** [comment] 2015-12-26 20:58
Hi, there are some variables inside imported js with require like count and collectionName. Count variable were changing anormally and collectionName too. I defined them inside jx.store because they should be unique for every thread i.e. thread safe. However that didnt work too. As you see above , i trace collectionName on its first assigment and then trace again with timeout. As you can see that changes. It is not the same with first assignment. Additional info, i dont if it is required but there is no node-gyp built

**Comment by ktrzeciaknubisa** [comment] 2015-12-27 12:33
@fatihpolatli When you speak of `jxcore.store` I hope you mean `jxcore.store.shared`, since this one is designed for multi-threading access. 

Also, we really need to see a bit of the code responsible for store access (hidden in your *reportAccessLevelBatch2jx.js*). Can you reduce it to minimal few-lines-code snippet?

**Comment by fatihpolatli** [comment] 2015-12-28 07:17
hi, 

this is some code from reportAccessLevelBatch2jx.js,

	jxcore.store.set("count", 0);

	module.exports = function() {
	    return {
	        initialize: initialize,
	        setCollectionName: setCollectionName,
	        setDataService: setDataService,
	        getCollectionName: getCollectionName
	    }
	}


	function setCollectionName(cName) {

	    jxcore.store.set("collectionName", cName);

	    console.log("INSIDE COLLECTION NAME : ", jxcore.store.read("collectionName"));
	 
	}

	function getCollectionName(){

	    return jxcore.store.read("collectionName");
	}

	function initialize() {

	  
	    console.log("this is batch");
	    console.log("collection name ss : " + jxcore.store.read("collectionName"))

	    MongoClient.connect('mongodb://mongoip:27017/metric', function(err, db) {
	        if (err) throw err;

	        globaldb = db;

	        biCollection = db.collection('biRepository');
	        console.log("collection");

	        initAfterFetch();
	    });

	}

	function initAfterFetch() {

	    try {
	        console.log("INIT AFTER FETCH");

	        var c = Number(jxcore.store.read("count"));
	        jxcore.store.set("count", c + 1);

	        var cc = jxcore.store.read("count");

	        getReportsForUserAccess(allUsers[cc]);

	    } catch (e) {

	        console.log(e);
	    }
	}

**Comment by ktrzeciaknubisa** [comment] 2015-12-28 18:44
Thanks. I see here that `initAfterFetch` is called in async way, since `MongoClient.connect` is working async in first place. Thus it cannot guarantee the order of `jxcore.store.set("count", c + 1);` execution. Maybe that is the reason of your concern?

**Comment by fatihpolatli** [comment] 2015-12-28 18:51
@ktrzeciaknubisa 
first of all thanks for your effort, i call "initialize" function after "setCollectionName", so after setting all i need, i call initialize

**Comment by ktrzeciaknubisa** [comment] 2015-12-29 10:31
@fatihpolatli You're welcome.

I think I know what's going on here. Let's keep in mind, that when you call `jxcore.tasks.addTask()` it doesn't mean that each task will have its own thread. You may have 30 tasks, but only 4/8/16 etc physical cores (threads). But even if you had enough cores, when using `addTask()` there is still a chance, that some of the tasks will run on the same thread (and share the same `jxcore.strore`). 

It's in the [docs](http://jxcore.com/docs/jxcore-tasks.html#tasksaddtaskmethod-param-callback) :

> If for example on your system getThreadCount() returns 3, and you add 3 tasks one after another, there is no guarantee, that each of them will run in its own sub-instance, but still it is one of the possibilities. But things can go also in many other ways: all of the 3 tasks can run in the same sub-instance, or two of them in one, and the third in another, etc.

**Comment by fatihpolatli** [comment] 2015-12-29 10:34
@ktrzeciaknubisa 

Hi,

I understand,but how do you handle that then?

**Comment by ktrzeciaknubisa** [comment] 2015-12-29 10:43
Depends on what you want to do exactly. 

1. If you need collection per task (not per thread), you may just use regular object `{}` instead of `jxcore.store`.
2. If you don't need 30 tasks, or you want number of tasks to be equal to number of threads, then you can use [jxcore.tasks.runOnce()](http://jxcore.com/docs/jxcore-tasks.html#tasksrunoncemethod-param-donotremember)

**Comment by fatihpolatli** [comment] 2015-12-29 10:45
@ktrzeciaknubisa

Thanks, i will check it out

**Comment by obastemur** [comment] 2016-01-05 23:25
@fatihpolatli closing this `none` issue. Thanks for the thread and details. There must be others with similar questions.

**Closed by obastemur** 2016-01-05 23:25 UTC
