### ISSUE TITLE
discuss: how jxcore should approach to node 0.12.0?

### ISSUE THREAD

**Issue by darrrk** [jxcore/jxcore#176] opened 2015-02-13 22:18 UTC

**Comment by obastemur** [comment] 2015-02-17 16:46
This will be a broad subject to discuss. We are releasing jxcore with multiple engines http://jxcore.io , and we will have latest ES6 features from SpiderMonkey. 

So far we didn't want to break node10 compatibility, since most node modules are compatible to node10. We may introduce the handy features from node12 but there are multiple ways to do that. 

This is an open subject and I'm wondering what others would say. How jxcore should approach to node12 is the real question here.

**Comment by darrrk** [comment] 2015-02-17 20:20
Maybe freeze jxcore version, which based on node 0.10.x and develop new version, which based on node 0.12.x
I think npm community with time will go to node 0.12.x, as it was before 0.8.x to 0.10.x

**Comment by obastemur** [comment] 2015-02-19 07:33
Actually current JXcore has the base for 0.12(commons interface). I mean we can quickly move the things back and forward. On the other hand, SpiderMonkey (SM) build is already answering all the ES6 needs (even more..)

So the possibilities / questions are:
 - Bring the extras from 0.12 without breaking the core. (Any urgent feature? Lets make a list)
 - Update V8 to latest (for what reason? how urgent is this after latest SM?)

What should we do ?

**Comment by darrrk** [comment] 2015-02-19 12:02
> So far we didn't want to break node10 compatibility
> ...
> We may introduce the handy features from node12

node12 has breaking changes, for example, http://strongloop.com/strongblog/node-js-v0-12-apis-breaking/

**Comment by martinies** [comment] 2015-02-20 09:06
nodejs really needs a common and stable native interface. npm already turned into an incompatible modules archive. Anyway, V8 on node 0.12 is faster than the one on node 0.10. Also lots of ES6 features. I 'definitely' can not say node 0.12 faster comparing to node 0.10. don't know why. 

From the javascript engine point, jxcore has latest SpiderMonkey, and it feels also very fast + asmjs! 

My wish here is that I would like to have a stable jxcore as soon as possible. I believe, it's very early to move on node 0.12 . node 0.10 has a very stable base and almost all the required api. 

First make jxcore stable than move on 0.12 (api) ?

**Comment by darrrk** [comment] 2015-02-20 10:45
Ok, maybe at first to release stable jxcore version, based on node10
Then release next jxcore, based on node12
Seems like trade off way

**Comment by ukadakal** [comment] 2015-02-20 17:22
I think it makes sense to wait until Node.JS and io.js come to terms with the new foundation and technical governance of the project. If those two projects merge, it means there will be a different version with a different version of V8.

**Comment by obastemur** [comment] 2015-02-27 01:39
It seems like there won't be a node 0.12.x Instead it will be a node 1.0.x with same features.

I agree with @ukadakal .  JXcore is a project that extends node.js's capabilities to other platforms + additional features. Current node 0.10.x baseline is stable enough for the first stable JXcore release. We may come back to this subject whenever things are more clear on node.js side.

I believe it won't take much time to update JXcore's API base to next node. JXcore by design already compatible to latest V8 (commons interface) and it already uses some design updates from latest libuv. Besides, JXcore has latest SpiderMonkey option with latest ES6, ASM.JS .. support.

**Comment by cref** [comment] 2015-03-06 14:46
To me, being able to use ES6 is the most useful feature of node 0.12.x. It's fine if jxcore only offers ES6 through the SpiderMonkey backend but how can I get/perform a Windows build for that?

**Comment by dschaadt** [comment] 2015-03-09 11:25
I played around today with the sources from jxcore master and the v8 engine embedded in io.js 1.5.0. I tried to compile jxcore on windows using V8 from io.js 1.5.0, but failed horribly due to a no longer matching common interface. Therefore, to me it looks like it will not be that easy to embed a new V8 since they changed many things such as removing invocationcallback etc, which breaks for instance the macro definitions in PMacro.h and produces numerous other errors. Unfortunately, I do not know enough with C/C++ and V8 to help out further. I still feel however to base jxcore at least somewhat on the fast development in io.js, and not the sluggish node progress. Instead of focussing on too many issues such as different platforms, it might be best to first update the codebase to the current state-of-the-art. I am afraid that the great ideas about multithreading in jxcore get lost if the whole projects diverts into too many directions loosing focus...

**Comment by obastemur** [comment] 2015-03-09 12:37
@dschaadt  just replacing V8 source base is indeed not enough :) It's all about updating the macro definitions (this might require C/C++ exp), thanks to jxcore's modern and flexible code base, this wouldn't take much time. The question is; why would we rush on this? node 0.12+ is not stable as much as jxcore(v8) or node 0.10.x. Besides, JXcore already updated many critical stuff node 0.12 has.  

We do not depend on the development speed of both sides. I think JXcore's update rate is incomparable. Find a 'diff' tool and see yourself. (compare node 0.12 / io  to node 0.10) and do the same for JXcore. 

JXcore's direction is very clear. It targets many more platforms and offers must to have features for those platforms and others. No worries. Multithreading can't go anywhere, since cluster etc. are useless on mobile platforms and shared hosting environments. 

We are not forcing JXcore on server platforms as long as you don't need the extra features but if you need them, current node/io.js 'state-of-art' need big updates to catch-up with JXcore. 

If you are interested helping us to make multithreading better, you are very welcome!

@cref I'm working on moving nsprpub into Windows builds. SpiderMonkey needs it on Windows. Soon it should be ready.

**Comment by plika** [comment] 2015-07-08 03:55
closing this issue in favor of https://github.com/jxcore/jxcore/issues/402

**Closed by plika** 2015-07-08 03:55 UTC
