### ISSUE TITLE
Android doesn't like gz files in node_modules

### ISSUE THREAD

**Issue by yaronyg** [jxcore/jxcore#236] opened 2015-03-15 22:06 UTC
This is a related but still separate issue from #235.

When I tried to do a build with a bunch of files in node_modules, after deleting the specific *.gz files mentioned in #235 I ran into a new error - java.util.zip.ZipException: invalid code lengths set

Having done some research on this exception in general it seemed to have something to do with compressing already compressed content. So my current work around is to delete all the *.gz files in node_modules.

Even if by some miracle this "delete all *.gz" files approach works in my case it's not something I want to depend on. We need some way to get gz files safely through Android's asset packager.

**Comment by obastemur** [comment] 2015-03-15 22:25
So the case to reproduce here is to put a .gz file into assets folder and try to read it over jxcore 'fs' ?

**Comment by yaronyg** [comment] 2015-03-16 00:55
Actually I didn't even try to read it at all because the Android build fails! In other words, the mere presence of the gz files makes it impossible to build the project! I believe the specific problem files were the gzip-*.gz files in pouchdb\node_modules\watchify\node_modules\browserify\node_modules\browserify-zlib\node_modules\pako\test\fixtures.

In other words, it's part of pako but I got it via a long chain.

**Comment by obastemur** [comment] 2015-03-17 00:04
Seems like Android APK manager doesn't accept gz files. @ktrzeciaknubisa could you please test a basic .jx file with the sample iOS and Android apps ?

**Comment by ktrzeciaknubisa** [comment] 2015-03-17 10:14
#### Android

1. I can confirm that having inside *asset* folder any file with **.gz** extension (it doesn't have to be a gzip archive - could be a text file or any other with **.gz** ext name) prevents Eclipse's build. For me the error was as follows:

> [2015-03-17 10:42:57 - jxcore-droid]       Unable to add '/[...]/jxcore-android-basics/jxcore-droid/assets/jxcore/test.js.gz': file already in archive (try '-u'?)
[2015-03-17 10:42:57 - jxcore-droid] ERROR: unable to process assets while packaging '/[...]/jxcore-android-basics/jxcore-droid/bin/resources.ap_'
[2015-03-17 10:42:57 - jxcore-droid] ERROR: packaging of '/[...]/jxcore-android-basics/jxcore-droid/bin/resources.ap_' failed

2. You can embed gzip files, as long as you rename the extension into something else that **.gz**

3. jx packages are fine as assets: 
 * Eclipse builds properly 
 * app is executable
 * jx package is callable by the application

#### iOS

1. jx packages - all good, can be callable by an app

2. even though there was no case to test .gz files for iOS apps I tested and they do not rise any problems

**Comment by obastemur** [comment] 2015-03-17 10:28
@ktrzeciaknubisa thanks for the details. Closing this issue. I think it has not much to do with JXcore.

**Closed by obastemur** 2015-03-17 10:28 UTC

**Comment by yaronyg** [comment] 2015-03-17 15:58
I would ask you to please reconsider closing this bug. I believe there is an issue here and I can see two potential resolutions. 

Resolution #1 - A warning - Text needs to be added to the readme saying "JXCore packages Node.js files on Android in such a way that any gz file will be rejected. So even though Node.js supports gz files, JXCore on Android does not. So please avoid any gz file use, at least if you intend to run your code on Android."

Resolution #2 - Fix the bug. There are plenty of ways to do this. You can put in a filter that translates gz file names to something else and then translates them back. You can store files differently. Etc.

**Comment by obastemur** [comment] 2015-03-17 16:07
@yaronyg we don't have anything to do with Android compilation process or creation of APK file. Android's toolchain is responsible from compiling / deploying everything.  Perhaps I'm missing the point here. Could you be more precise.

**Comment by obastemur** [comment] 2015-03-17 16:09
In other words, create an empty Android project (no jxcore or anything else), put a .gz file into assets folder and 'bam!' you will have this error / warning..

**Comment by yaronyg** [comment] 2015-03-17 16:25
From the perspective of an Android developer you are absolutely right. Any Android developer would know not to put gz files into assets.

But I would suggest that the perspective we should be looking at this from is not an Android developer, but rather a node.js developer.

As a node.js developer I want to write some Node.js code and then use JXCore to deploy it on iOS, on Android, on WinRT, on Linux, on OS/X and on Win32. I do not want to deal with the idiosyncrasies of each of those platforms. That's the whole point of using JXCore. I depend on it to handle those idiosyncrasies for me.

So now imagine that you are a node.js developer. You 'npm install semver' and you run your code on Win32 and it works fine. You run on Linux and it works fine. You run it on OS/X and it works fine. You run it on iOS and it works fine. Then you get to Android and suddenly your code that worked fine everywhere else won't even compile! What's going on?

As a node.js developer I don't want to deal with this. I depend on JXCore to handle platform issues for me. If Android has a problem with gz files I expect JXCore to deal with that and just make node.js work.

Now do you see why I at least think this is a problem that JXCore needs to address?

**Comment by obastemur** [comment] 2015-03-17 16:35
I think I got your point. We already have a solution to this problem.

When it comes to file system, node.js / jxcore core library 'fs' already has many issues / differences with multi platform consistency. This is one of the reasons why we have JX packaging feature. When you JX package your solution, you may expect that it will be fine on iOS, Android, OSX, Windows etc..

**Comment by yaronyg** [comment] 2015-03-18 00:22
Will packaging work with Cordova? Also is packaging also open source?

**Comment by ktrzeciaknubisa** [comment] 2015-03-18 11:33
> Will packaging work with Cordova?

Sure, you can use any jx package within Cordova application and use it as it would be js file. I've tested this.

> Also is packaging also open source?

Yes, it is. However, if you would look also after source code protection (which is related to packaging) - it cannot be guaranteed once it's open sourced.

**Comment by yaronyg** [comment] 2015-03-18 17:52
That actually all sounds great to me! If we are able to precompile the JS how much of a perf improvement will that give? Any idea?

**Comment by obastemur** [comment] 2015-03-18 18:36
It wouldn't give any performance gain (as far as I had tested before). but this is for giving a hard time to the curious people want to see your source codes. Currently, all the JavaScript mobile solutions are suffering from this problem.

**Comment by ktrzeciaknubisa** [comment] 2015-07-02 12:57
@yaronyg I'm just adding a new note to the old topic: when you're installing an npm module with `jx install` command you can use [--autoremove](https://github.com/jxcore/jxcore/blob/master/doc/api/jxcore-command-install.markdown#install) option for .gz files cleanup. A little helper for the problem :) There is also a discussion at #390 .
