### ISSUE TITLE
Plesk - Internal error on activation

### ISSUE THREAD

**Issue by bert-teng** [jxcore/jxcore#487] opened 2015-08-12 18:46 UTC
This happened after clicking 'OK' to agree to the terms and condition.
![screen shot 2015-08-12 at 11 44 04 am](https://cloud.githubusercontent.com/assets/5497639/9233415/aed5e23e-40e7-11e5-8e76-c553fcecc115.png)

I'm running Plesk 12.0.18 Update #59, CentOS 6.7

**Comment by ktrzeciaknubisa** [comment] 2015-08-12 19:39
Oh yes, thank you. There is visible problem, although it newer came up on our platforms. This may be related to the fact, that we don't have E_NOTICE outputting enabled as probably you do in `/usr/local/psa/admin/conf/php.ini` (error_reporting). 

Although I made a fix and until it will be official you can take it from [dev JXcore for Plesk extension 0.2.7-2](https://github.com/ktrzeciaknubisa/jxcore-issues/raw/master/plesk/dev/JXcore_Plesk0272.zip), I'd like to ask you to make the following test before applying it:

1. edit `/usr/local/psa/admin/conf/php.ini`
2. disable notices by `error_reporting = E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED`
3. save
4. restart sw-engine `/etc/init.d/sw-cp-server restart`

Now try to apply the official latest extension and see how it goes!

**Comment by bert-teng** [comment] 2015-08-12 22:20
@ktrzeciaknubisa Thanks for your response! We tried the test you provided and we are still seeing the notification so we applied the fix from your link.

Using the 0.2.7-2 build, the installation and activation works perfect but we are still seeing the following
![screen shot 2015-08-12 at 3 14 15 pm](https://cloud.githubusercontent.com/assets/5497639/9238163/24abd096-4105-11e5-829c-638d363601d2.png)

This is when we tried to enable JXcore on a domain. However, this notice disappear when we refreshed the page but any attempt to click on "JXcore Application Log" or "Restart Manager" will result in that error message re-appearing.

**Comment by ktrzeciaknubisa** [comment] 2015-08-13 08:46
We have the exact Plesk platform but I not able to reproduce this. This will need some debugging steps to be taken. Are you ready to work with me on mail? May I use the mail address from your profile?

**Comment by bert-teng** [comment] 2015-08-13 15:49
Yea, definitely. You can reach through that email address.

On Thursday, August 13, 2015, Krzysztof Trzeciak <notifications@github.com>
wrote:

> We have the exact Plesk platform but I not able to reproduce this. This
> will need some debugging steps to be taken. Are you ready to work with me
> on mail? May I use the mail address from your profile?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jxcore/jxcore/issues/487#issuecomment-130578321>.
>


-- 
*ALBERT*
*Developer*
*____________*

*SKYROCKET*
Design for tomorrow <http://skyrocket.is/>

+1 604-563-6330
301 - 560 Beatty Street, Vancouver, BC V6B 2L3

Pinterest <http://pinterest.com/skyrocketMP/> : Facebook
<https://www.facebook.com/SKYRKT> : Twitter <https://twitter.com/skyrkt> :
LinkedIn <http://www.linkedin.com/company/skyrkt>

*--*

**Comment by ktrzeciaknubisa** [comment] 2015-08-13 22:07
Closing the issue since during mail/skype conversation with @bert-teng we were unable to recreate the problem. For now the issue disappeared, as @bert-teng reported. Probably specific php version / settings could trigger the error, but since php was reinstalled on user's machine, the error is not showing up anymore. 

We'll see if it comes back.

**Closed by ktrzeciaknubisa** 2015-08-13 22:07 UTC
