### ISSUE TITLE
mongodb driver won't load in native windows .exe

### ISSUE THREAD

**Issue by nevf** [jxcore/jxcore#773] opened 2016-01-11 10:26 UTC
I have index.js as follows:
````
var mongodb = require('mongodb');
console.log('mongodb driver loader!');
````
I've installed mongodb using jx install and it is V2.1.3

If I run the app ```jx myapp`` it displays 'mongodb driver loader!'
If I compile it as a --native app and run the .exe I don't see the console log message and the driver hasn't loaded. I am running jx v0.3.1.0

I have the same issue in a fully blown app and replicated it here in this 2 liner.

**Comment by ktrzeciaknubisa** [comment] 2016-01-11 11:13
I don't reproduce this on Windows 7. Which Windows are you using? 

I do get console output with both `--native` and non `--native` and I don't even have mongo database engine installed.

**Comment by nevf** [comment] 2016-01-11 19:55
@ktrzeciaknubisa Thanks for the prompt reply. I am using Windows 10.

When I run ```jx package index.js mongo``` I get:
````
....
Warning! ....erberos\build\Release\kerberos.node
Adding a .node (native) file into package may fail the application
Check the related discussion from https://github.com/jxcore/jxcore/issues/101
However you may mark .node files as extractable, e.g.: --extract-what '*.node'
````

I suspect that the kerberos native module is causing this problem. I am very new to jx and will need to dig around the doc's to try and resolve this.  Any help appreciated.

**Comment by nevf** [comment] 2016-01-11 20:36
I've updated my mongo.jxp file as follows:
````
	"extract": {
		"what": [
			"*.node"
		],
		"where": "./",
        "message" : "Extracting now...",
        "verbose" : true,
        "overwrite" : true
	},
       .....
	"assets": [
		"node_modules\\mongodb\\node_modules\\kerberos\\build\\Release\\kerberos.node"
	],
        ....
````

then run:
```jjx compile mongo.jxp --native``` 
````
> mongo
Extracting now...
extracting .\node_modules\mongodb\node_modules\kerberos\build\Release\kerberos.node
````
and still no console.log message.  Compiling and executing without --native still works.

**Comment by ktrzeciaknubisa** [comment] 2016-01-11 20:45
Yes, I was just going to mention, that marking .node files as extractable is the key. 

Are you using `process.exit()` or the app just finishes by itself? I'm asking, because we know about some `console.log()` flushing problems when using `process.exit()`.

**Comment by ktrzeciaknubisa** [comment] 2016-01-11 20:54
Ah, one more thing. You may need to rename your `app.exe` into `jx.exe`. See if it applies to your case: https://github.com/jxcore/jxcore/issues/489#issuecomment-153398763 .

**Comment by ktrzeciaknubisa** [comment] 2016-01-11 21:02
I think I **did** reproduce the problem after all. And yes, renaming `app.exe` into `jx.exe` made it working.

**Comment by nevf** [comment] 2016-01-11 21:14
@ktrzeciaknubisa I'm not using ```process.exit()``` just the 2 lines in my original post. 

And yes if I rename ```app.exe``` to ```jx.exe``` it works now. I read #489 but I don't understand why this is causing the problem or why it resolves it. Are there plans to allow us to name the .exe as required?

**Comment by ktrzeciaknubisa** [comment] 2016-01-11 22:48
@nevf This is because .node files are compiled against `jx.exe` (this exact file name is hard-coded into .node files), thus when you run `app.exe`, the extracted e.g. `kerberos.node` expects it to be `jx.exe`.

I'm closing this for now, as the main problem already is described in #489 .

**Closed by ktrzeciaknubisa** 2016-01-11 22:48 UTC
